// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.2
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _image_filter_Block_entry_proc136_HH_
#define _image_filter_Block_entry_proc136_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct image_filter_Block_entry_proc136 : public sc_module {
    // Port declarations 10
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<3> > return_r;
    sc_out< sc_logic > return_r_ap_vld;
    sc_in< sc_lv<3> > ges_load1341;


    // Module declarations
    image_filter_Block_entry_proc136(sc_module_name name);
    SC_HAS_PROCESS(image_filter_Block_entry_proc136);

    ~image_filter_Block_entry_proc136();

    sc_trace_file* mVcdFile;

    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<1> > ap_CS_fsm;
    sc_signal< bool > ap_sig_bdd_27;
    sc_signal< sc_lv<3> > return_r_preg;
    sc_signal< sc_lv<1> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<1> ap_ST_st1_fsm_0;
    static const sc_lv<3> ap_const_lv3_0;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sig_bdd_27();
    void thread_return_r();
    void thread_return_r_ap_vld();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
