// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.2
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _set_color_HH_
#define _set_color_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct set_color : public sc_module {
    // Port declarations 22
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<12> > src_rows_V_read;
    sc_in< sc_lv<12> > src_cols_V_read;
    sc_in< sc_lv<8> > src_data_stream_0_V_dout;
    sc_in< sc_logic > src_data_stream_0_V_empty_n;
    sc_out< sc_logic > src_data_stream_0_V_read;
    sc_out< sc_lv<8> > dst_data_stream_0_V_din;
    sc_in< sc_logic > dst_data_stream_0_V_full_n;
    sc_out< sc_logic > dst_data_stream_0_V_write;
    sc_out< sc_lv<8> > dst_data_stream_1_V_din;
    sc_in< sc_logic > dst_data_stream_1_V_full_n;
    sc_out< sc_logic > dst_data_stream_1_V_write;
    sc_out< sc_lv<8> > dst_data_stream_2_V_din;
    sc_in< sc_logic > dst_data_stream_2_V_full_n;
    sc_out< sc_logic > dst_data_stream_2_V_write;
    sc_in< sc_lv<3> > ges;


    // Module declarations
    set_color(sc_module_name name);
    SC_HAS_PROCESS(set_color);

    ~set_color();

    sc_trace_file* mVcdFile;

    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<2> > ap_CS_fsm;
    sc_signal< sc_lv<12> > t_V_reg_114;
    sc_signal< bool > ap_sig_bdd_48;
    sc_signal< sc_lv<1> > tmp_s_fu_126_p2;
    sc_signal< sc_lv<1> > tmp_s_reg_246;
    sc_signal< sc_lv<1> > tmp_9_fu_132_p2;
    sc_signal< sc_lv<1> > tmp_9_reg_251;
    sc_signal< sc_lv<12> > i_V_fu_143_p2;
    sc_signal< sc_lv<12> > i_V_reg_259;
    sc_signal< sc_lv<1> > exitcond_fu_149_p2;
    sc_signal< sc_lv<1> > exitcond_reg_264;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it0;
    sc_signal< bool > ap_sig_bdd_70;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it1;
    sc_signal< sc_lv<1> > ap_reg_ppstg_exitcond_reg_264_pp0_it1;
    sc_signal< bool > ap_sig_bdd_84;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it2;
    sc_signal< sc_lv<12> > j_V_fu_154_p2;
    sc_signal< sc_lv<1> > tmp_27_fu_160_p1;
    sc_signal< sc_lv<1> > tmp_27_reg_273;
    sc_signal< sc_lv<1> > tmp_24_not_fu_164_p2;
    sc_signal< sc_lv<1> > tmp_24_not_reg_280;
    sc_signal< sc_lv<1> > brmerge_fu_170_p2;
    sc_signal< sc_lv<1> > brmerge_reg_285;
    sc_signal< sc_lv<1> > exitcond4_fu_138_p2;
    sc_signal< sc_lv<12> > t_V_7_reg_103;
    sc_signal< sc_lv<1> > brmerge1_fu_180_p2;
    sc_signal< sc_lv<1> > not_brmerge1_fu_189_p2;
    sc_signal< sc_lv<1> > pixel_out_val_1_3_fu_195_p2;
    sc_signal< sc_lv<1> > not_brmerge_fu_184_p2;
    sc_signal< sc_lv<1> > tmp2_fu_205_p2;
    sc_signal< sc_lv<1> > pixel_out_val_1_fu_211_p2;
    sc_signal< sc_lv<1> > not_tmp_24_not_fu_175_p2;
    sc_signal< sc_lv<1> > tmp3_fu_221_p2;
    sc_signal< sc_lv<1> > pixel_out_val_0_fu_226_p2;
    sc_signal< sc_lv<2> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<2> ap_ST_st1_fsm_0;
    static const sc_lv<2> ap_ST_st2_fsm_1;
    static const sc_lv<2> ap_ST_pp0_stg0_fsm_2;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<12> ap_const_lv12_0;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<3> ap_const_lv3_1;
    static const sc_lv<12> ap_const_lv12_1;
    static const sc_lv<8> ap_const_lv8_FF;
    static const sc_lv<1> ap_const_lv1_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sig_bdd_48();
    void thread_ap_sig_bdd_70();
    void thread_ap_sig_bdd_84();
    void thread_brmerge1_fu_180_p2();
    void thread_brmerge_fu_170_p2();
    void thread_dst_data_stream_0_V_din();
    void thread_dst_data_stream_0_V_write();
    void thread_dst_data_stream_1_V_din();
    void thread_dst_data_stream_1_V_write();
    void thread_dst_data_stream_2_V_din();
    void thread_dst_data_stream_2_V_write();
    void thread_exitcond4_fu_138_p2();
    void thread_exitcond_fu_149_p2();
    void thread_i_V_fu_143_p2();
    void thread_j_V_fu_154_p2();
    void thread_not_brmerge1_fu_189_p2();
    void thread_not_brmerge_fu_184_p2();
    void thread_not_tmp_24_not_fu_175_p2();
    void thread_pixel_out_val_0_fu_226_p2();
    void thread_pixel_out_val_1_3_fu_195_p2();
    void thread_pixel_out_val_1_fu_211_p2();
    void thread_src_data_stream_0_V_read();
    void thread_tmp2_fu_205_p2();
    void thread_tmp3_fu_221_p2();
    void thread_tmp_24_not_fu_164_p2();
    void thread_tmp_27_fu_160_p1();
    void thread_tmp_9_fu_132_p2();
    void thread_tmp_s_fu_126_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
