// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.2
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================


`timescale 1ns/1ps

module image_filter_sitodp_64s_64_9
#(parameter
    ID         = 45,
    NUM_STAGE  = 9,
    din0_WIDTH = 64,
    dout_WIDTH = 64
)(
    input  wire                  clk,
    input  wire                  reset,
    input  wire                  ce,
    input  wire [din0_WIDTH-1:0] din0,
    output wire [dout_WIDTH-1:0] dout
);
//------------------------Local signal-------------------
wire                  aclk;
wire                  aclken;
wire                  a_tvalid;
wire [63:0]           a_tdata;
wire                  r_tvalid;
wire [63:0]           r_tdata;
reg  [din0_WIDTH-1:0] din0_buf1;
reg  [dout_WIDTH-1:0] out_buf0;
reg  [dout_WIDTH-1:0] out_buf1;
reg  [dout_WIDTH-1:0] out_buf2;
reg  [dout_WIDTH-1:0] out_buf3;
reg  [dout_WIDTH-1:0] out_buf4;
reg  [dout_WIDTH-1:0] out_buf5;
//------------------------Instantiation------------------
itodp_v7 itodp_v7_u (
    .aclk                 ( aclk ),
    .aclken               ( aclken ),
    .s_axis_a_tvalid      ( a_tvalid ),
    .s_axis_a_tdata       ( a_tdata ),
    .m_axis_result_tvalid ( r_tvalid ),
    .m_axis_result_tdata  ( r_tdata )
);
//------------------------Body---------------------------
assign aclk     = clk;
assign aclken   = ce;
assign a_tvalid = 1'b1;
assign a_tdata  = din0_buf1;
assign dout     = out_buf5;

always @(posedge clk) begin
    if (ce) begin
        din0_buf1 <= din0;
    end
end

always @ (posedge clk) begin
    if (ce) begin
        out_buf0 <= r_tdata;
        out_buf1 <= out_buf0;
        out_buf2 <= out_buf1;
        out_buf3 <= out_buf2;
        out_buf4 <= out_buf3;
        out_buf5 <= out_buf4;
    end
end
endmodule
