-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2013.2
-- Copyright (C) 2013 Xilinx Inc. All rights reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Sobel_1_0_3_16_16_1080_1920_1080_1920_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_src_rows_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
    p_src_cols_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
    p_src_data_stream_0_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    p_src_data_stream_0_V_empty_n : IN STD_LOGIC;
    p_src_data_stream_0_V_read : OUT STD_LOGIC;
    p_src_data_stream_1_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    p_src_data_stream_1_V_empty_n : IN STD_LOGIC;
    p_src_data_stream_1_V_read : OUT STD_LOGIC;
    p_src_data_stream_2_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    p_src_data_stream_2_V_empty_n : IN STD_LOGIC;
    p_src_data_stream_2_V_read : OUT STD_LOGIC;
    p_dst_data_stream_0_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_dst_data_stream_0_V_full_n : IN STD_LOGIC;
    p_dst_data_stream_0_V_write : OUT STD_LOGIC;
    p_dst_data_stream_1_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_dst_data_stream_1_V_full_n : IN STD_LOGIC;
    p_dst_data_stream_1_V_write : OUT STD_LOGIC;
    p_dst_data_stream_2_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_dst_data_stream_2_V_full_n : IN STD_LOGIC;
    p_dst_data_stream_2_V_write : OUT STD_LOGIC );
end;


architecture behav of Sobel_1_0_3_16_16_1080_1920_1080_1920_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_st1_fsm_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_ST_st2_fsm_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_st3_fsm_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_st4_fsm_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_ST_st5_fsm_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_ST_st6_fsm_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal a_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal a_ce0 : STD_LOGIC;
    signal a_q0 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_sig_bdd_64 : BOOLEAN;
    signal i_1_fu_212_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal i_1_reg_674 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_230_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_reg_679 : STD_LOGIC_VECTOR (4 downto 0);
    signal exitcond_fu_206_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp_fu_236_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp_reg_684 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp14_fu_242_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp14_reg_690 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp31_fu_260_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp31_reg_698 : STD_LOGIC_VECTOR (0 downto 0);
    signal j_1_fu_276_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal j_1_reg_752 : STD_LOGIC_VECTOR (1 downto 0);
    signal exitcond6_fu_270_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_99_fu_302_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_99_reg_762 : STD_LOGIC_VECTOR (0 downto 0);
    signal a_load_reg_769 : STD_LOGIC_VECTOR (2 downto 0);
    signal sel_tmp12_fu_332_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp12_reg_774 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp24_fu_337_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp24_reg_780 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp32_fu_342_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp32_reg_786 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp40_fu_353_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp40_reg_791 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp48_fu_358_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp48_reg_797 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond7_fu_369_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond7_reg_804 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond12_fu_378_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond12_reg_811 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_start : STD_LOGIC;
    signal grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_done : STD_LOGIC;
    signal grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_idle : STD_LOGIC;
    signal grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_ready : STD_LOGIC;
    signal grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_0_V_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_0_V_empty_n : STD_LOGIC;
    signal grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_0_V_read : STD_LOGIC;
    signal grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_1_V_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_1_V_empty_n : STD_LOGIC;
    signal grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_1_V_read : STD_LOGIC;
    signal grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_2_V_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_2_V_empty_n : STD_LOGIC;
    signal grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_2_V_read : STD_LOGIC;
    signal grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_0_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_0_V_full_n : STD_LOGIC;
    signal grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_0_V_write : STD_LOGIC;
    signal grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_1_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_1_V_full_n : STD_LOGIC;
    signal grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_1_V_write : STD_LOGIC;
    signal grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_2_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_2_V_full_n : STD_LOGIC;
    signal grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_2_V_write : STD_LOGIC;
    signal grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_0_0_V_read : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_0_1_V_read : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_0_2_V_read : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_1_0_V_read : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_1_1_V_read : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_1_2_V_read : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_2_0_V_read : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_2_1_V_read : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_2_2_V_read : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_rows : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_cols : STD_LOGIC_VECTOR (11 downto 0);
    signal i_reg_114 : STD_LOGIC_VECTOR (1 downto 0);
    signal j_reg_126 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_start_ap_start_reg : STD_LOGIC := '0';
    signal tmp_1_fu_291_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal kernel_val_0_0_V_fu_54 : STD_LOGIC_VECTOR (7 downto 0);
    signal kernel_val_2_2_V_16_fu_554_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal kernel_val_0_1_V_fu_58 : STD_LOGIC_VECTOR (7 downto 0);
    signal kernel_val_2_2_V_15_fu_539_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal kernel_val_0_2_V_1_fu_62 : STD_LOGIC_VECTOR (7 downto 0);
    signal kernel_val_0_2_V_fu_517_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal kernel_val_1_0_V_fu_66 : STD_LOGIC_VECTOR (7 downto 0);
    signal kernel_val_2_2_V_14_fu_488_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal kernel_val_1_1_V_fu_70 : STD_LOGIC_VECTOR (7 downto 0);
    signal kernel_val_2_2_V_13_fu_473_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal kernel_val_1_2_V_fu_74 : STD_LOGIC_VECTOR (7 downto 0);
    signal kernel_val_2_2_V_12_fu_458_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal kernel_val_2_0_V_fu_78 : STD_LOGIC_VECTOR (7 downto 0);
    signal kernel_val_2_2_V_11_fu_437_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal kernel_val_2_1_V_fu_82 : STD_LOGIC_VECTOR (7 downto 0);
    signal kernel_val_2_2_V_10_fu_429_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal kernel_val_2_2_V_1_fu_86 : STD_LOGIC_VECTOR (7 downto 0);
    signal kernel_val_2_2_V_fu_406_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_shl_fu_218_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_shl_cast_fu_226_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal i_cast_fu_202_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal sel_tmp29_fu_248_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp30_fu_254_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal j_cast_fu_266_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_282_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_1_fu_291_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_s_fu_282_p2_temp: signed (5-1 downto 0);
    signal tmp_98_fu_296_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal sel_tmp5_fu_308_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp7_fu_314_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp11_fu_326_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp39_fu_347_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp2_fu_320_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp3_fu_363_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp5_fu_374_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_fu_387_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond5_fu_391_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond11_fu_395_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond13_fu_401_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal kernel_val_2_2_V_fu_406_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal kernel_val_2_0_V_3_fu_384_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal a_load_reg_769_temp: signed (3-1 downto 0);
    signal newSel20_fu_414_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel20_fu_414_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel22_fu_421_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal kernel_val_2_2_V_11_fu_437_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel30_fu_444_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel30_fu_444_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel34_fu_451_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel36_fu_466_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel36_fu_466_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal kernel_val_2_2_V_6_fu_481_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal kernel_val_2_2_V_6_fu_481_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel37_fu_495_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel37_fu_495_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel38_fu_502_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel39_fu_509_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel_fu_525_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel_fu_525_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel40_fu_532_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel41_fu_547_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel41_fu_547_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);

    component filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        p_src_data_stream_0_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        p_src_data_stream_0_V_empty_n : IN STD_LOGIC;
        p_src_data_stream_0_V_read : OUT STD_LOGIC;
        p_src_data_stream_1_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        p_src_data_stream_1_V_empty_n : IN STD_LOGIC;
        p_src_data_stream_1_V_read : OUT STD_LOGIC;
        p_src_data_stream_2_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        p_src_data_stream_2_V_empty_n : IN STD_LOGIC;
        p_src_data_stream_2_V_read : OUT STD_LOGIC;
        p_dst_data_stream_0_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_dst_data_stream_0_V_full_n : IN STD_LOGIC;
        p_dst_data_stream_0_V_write : OUT STD_LOGIC;
        p_dst_data_stream_1_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_dst_data_stream_1_V_full_n : IN STD_LOGIC;
        p_dst_data_stream_1_V_write : OUT STD_LOGIC;
        p_dst_data_stream_2_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_dst_data_stream_2_V_full_n : IN STD_LOGIC;
        p_dst_data_stream_2_V_write : OUT STD_LOGIC;
        kernel_val_0_0_V_read : IN STD_LOGIC_VECTOR (7 downto 0);
        kernel_val_0_1_V_read : IN STD_LOGIC_VECTOR (7 downto 0);
        kernel_val_0_2_V_read : IN STD_LOGIC_VECTOR (7 downto 0);
        kernel_val_1_0_V_read : IN STD_LOGIC_VECTOR (7 downto 0);
        kernel_val_1_1_V_read : IN STD_LOGIC_VECTOR (7 downto 0);
        kernel_val_1_2_V_read : IN STD_LOGIC_VECTOR (7 downto 0);
        kernel_val_2_0_V_read : IN STD_LOGIC_VECTOR (7 downto 0);
        kernel_val_2_1_V_read : IN STD_LOGIC_VECTOR (7 downto 0);
        kernel_val_2_2_V_read : IN STD_LOGIC_VECTOR (7 downto 0);
        rows : IN STD_LOGIC_VECTOR (11 downto 0);
        cols : IN STD_LOGIC_VECTOR (11 downto 0) );
    end component;


    component Sobel_1_0_3_16_16_1080_1920_1080_1920_s_a IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;



begin
    a_U : component Sobel_1_0_3_16_16_1080_1920_1080_1920_s_a
    generic map (
        DataWidth => 3,
        AddressRange => 9,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => a_address0,
        ce0 => a_ce0,
        q0 => a_q0);

    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139 : component filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_start,
        ap_done => grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_done,
        ap_idle => grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_idle,
        ap_ready => grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_ready,
        p_src_data_stream_0_V_dout => grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_0_V_dout,
        p_src_data_stream_0_V_empty_n => grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_0_V_empty_n,
        p_src_data_stream_0_V_read => grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_0_V_read,
        p_src_data_stream_1_V_dout => grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_1_V_dout,
        p_src_data_stream_1_V_empty_n => grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_1_V_empty_n,
        p_src_data_stream_1_V_read => grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_1_V_read,
        p_src_data_stream_2_V_dout => grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_2_V_dout,
        p_src_data_stream_2_V_empty_n => grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_2_V_empty_n,
        p_src_data_stream_2_V_read => grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_2_V_read,
        p_dst_data_stream_0_V_din => grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_0_V_din,
        p_dst_data_stream_0_V_full_n => grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_0_V_full_n,
        p_dst_data_stream_0_V_write => grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_0_V_write,
        p_dst_data_stream_1_V_din => grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_1_V_din,
        p_dst_data_stream_1_V_full_n => grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_1_V_full_n,
        p_dst_data_stream_1_V_write => grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_1_V_write,
        p_dst_data_stream_2_V_din => grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_2_V_din,
        p_dst_data_stream_2_V_full_n => grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_2_V_full_n,
        p_dst_data_stream_2_V_write => grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_2_V_write,
        kernel_val_0_0_V_read => grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_0_0_V_read,
        kernel_val_0_1_V_read => grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_0_1_V_read,
        kernel_val_0_2_V_read => grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_0_2_V_read,
        kernel_val_1_0_V_read => grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_1_0_V_read,
        kernel_val_1_1_V_read => grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_1_1_V_read,
        kernel_val_1_2_V_read => grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_1_2_V_read,
        kernel_val_2_0_V_read => grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_2_0_V_read,
        kernel_val_2_1_V_read => grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_2_1_V_read,
        kernel_val_2_2_V_read => grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_2_2_V_read,
        rows => grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_rows,
        cols => grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_cols);




    -- the current state (ap_CS_fsm) of the state machine. --
    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_st1_fsm_0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    -- ap_done_reg assign process. --
    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_continue)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_ST_st6_fsm_5 = ap_CS_fsm) and not((ap_const_logic_0 = grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_done)))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_start_ap_start_reg assign process. --
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_start_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_start_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_ST_st2_fsm_1 = ap_CS_fsm) and not((exitcond_fu_206_p2 = ap_const_lv1_0)))) then 
                    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_start_ap_start_reg <= ap_const_logic_1;
                elsif ((ap_const_logic_1 = grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_ready)) then 
                    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_start_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    -- i_reg_114 assign process. --
    i_reg_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_ST_st3_fsm_2 = ap_CS_fsm) and not((ap_const_lv1_0 = exitcond6_fu_270_p2)))) then 
                i_reg_114 <= i_1_reg_674;
            elsif (((ap_ST_st1_fsm_0 = ap_CS_fsm) and not(ap_sig_bdd_64))) then 
                i_reg_114 <= ap_const_lv2_0;
            end if; 
        end if;
    end process;

    -- j_reg_126 assign process. --
    j_reg_126_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_ST_st5_fsm_4 = ap_CS_fsm)) then 
                j_reg_126 <= j_1_reg_752;
            elsif (((ap_ST_st2_fsm_1 = ap_CS_fsm) and (exitcond_fu_206_p2 = ap_const_lv1_0))) then 
                j_reg_126 <= ap_const_lv2_0;
            end if; 
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_ST_st4_fsm_3 = ap_CS_fsm)) then
                a_load_reg_769 <= a_q0;
                or_cond12_reg_811 <= or_cond12_fu_378_p2;
                or_cond7_reg_804 <= or_cond7_fu_369_p2;
                sel_tmp12_reg_774 <= sel_tmp12_fu_332_p2;
                sel_tmp24_reg_780 <= sel_tmp24_fu_337_p2;
                sel_tmp32_reg_786 <= sel_tmp32_fu_342_p2;
                sel_tmp40_reg_791 <= sel_tmp40_fu_353_p2;
                sel_tmp48_reg_797 <= sel_tmp48_fu_358_p2;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_ST_st2_fsm_1 = ap_CS_fsm)) then
                i_1_reg_674 <= i_1_fu_212_p2;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_ST_st3_fsm_2 = ap_CS_fsm)) then
                j_1_reg_752 <= j_1_fu_276_p2;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_ST_st5_fsm_4 = ap_CS_fsm)) then
                kernel_val_0_0_V_fu_54 <= kernel_val_2_2_V_16_fu_554_p3;
                kernel_val_0_1_V_fu_58 <= kernel_val_2_2_V_15_fu_539_p3;
                kernel_val_0_2_V_1_fu_62 <= kernel_val_0_2_V_fu_517_p3;
                kernel_val_1_0_V_fu_66 <= kernel_val_2_2_V_14_fu_488_p3;
                kernel_val_1_1_V_fu_70 <= kernel_val_2_2_V_13_fu_473_p3;
                kernel_val_1_2_V_fu_74 <= kernel_val_2_2_V_12_fu_458_p3;
                kernel_val_2_0_V_fu_78 <= kernel_val_2_2_V_11_fu_437_p3;
                kernel_val_2_1_V_fu_82 <= kernel_val_2_2_V_10_fu_429_p3;
                kernel_val_2_2_V_1_fu_86 <= kernel_val_2_2_V_fu_406_p3;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_ST_st2_fsm_1 = ap_CS_fsm) and (exitcond_fu_206_p2 = ap_const_lv1_0))) then
                sel_tmp14_reg_690 <= sel_tmp14_fu_242_p2;
                sel_tmp31_reg_698 <= sel_tmp31_fu_260_p2;
                sel_tmp_reg_684 <= sel_tmp_fu_236_p2;
                tmp_reg_679 <= tmp_fu_230_p2;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_ST_st3_fsm_2 = ap_CS_fsm) and (ap_const_lv1_0 = exitcond6_fu_270_p2))) then
                tmp_99_reg_762 <= tmp_99_fu_302_p2;
            end if;
        end if;
    end process;

    -- the next state (ap_NS_fsm) of the state machine. --
    ap_NS_fsm_assign_proc : process (ap_CS_fsm , ap_sig_bdd_64 , exitcond_fu_206_p2 , exitcond6_fu_270_p2 , grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_done)
    begin
        case ap_CS_fsm is
            when ap_ST_st1_fsm_0 => 
                if (not(ap_sig_bdd_64)) then
                    ap_NS_fsm <= ap_ST_st2_fsm_1;
                else
                    ap_NS_fsm <= ap_ST_st1_fsm_0;
                end if;
            when ap_ST_st2_fsm_1 => 
                if ((exitcond_fu_206_p2 = ap_const_lv1_0)) then
                    ap_NS_fsm <= ap_ST_st3_fsm_2;
                else
                    ap_NS_fsm <= ap_ST_st6_fsm_5;
                end if;
            when ap_ST_st3_fsm_2 => 
                if ((ap_const_lv1_0 = exitcond6_fu_270_p2)) then
                    ap_NS_fsm <= ap_ST_st4_fsm_3;
                else
                    ap_NS_fsm <= ap_ST_st2_fsm_1;
                end if;
            when ap_ST_st4_fsm_3 => 
                ap_NS_fsm <= ap_ST_st5_fsm_4;
            when ap_ST_st5_fsm_4 => 
                ap_NS_fsm <= ap_ST_st3_fsm_2;
            when ap_ST_st6_fsm_5 => 
                if (not((ap_const_logic_0 = grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_done))) then
                    ap_NS_fsm <= ap_ST_st1_fsm_0;
                else
                    ap_NS_fsm <= ap_ST_st6_fsm_5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    a_address0 <= tmp_1_fu_291_p1(4 - 1 downto 0);

    -- a_ce0 assign process. --
    a_ce0_assign_proc : process(ap_CS_fsm, exitcond6_fu_270_p2)
    begin
        if (((ap_ST_st3_fsm_2 = ap_CS_fsm) and (ap_const_lv1_0 = exitcond6_fu_270_p2))) then 
            a_ce0 <= ap_const_logic_1;
        else 
            a_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_done assign process. --
    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_done)
    begin
        if (((ap_const_logic_1 = ap_done_reg) or ((ap_ST_st6_fsm_5 = ap_CS_fsm) and not((ap_const_logic_0 = grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_done))))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_idle assign process. --
    ap_idle_assign_proc : process(ap_start, ap_CS_fsm)
    begin
        if ((not((ap_const_logic_1 = ap_start)) and (ap_ST_st1_fsm_0 = ap_CS_fsm))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_ready assign process. --
    ap_ready_assign_proc : process(ap_CS_fsm, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_done)
    begin
        if (((ap_ST_st6_fsm_5 = ap_CS_fsm) and not((ap_const_logic_0 = grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_done)))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_bdd_64 assign process. --
    ap_sig_bdd_64_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_sig_bdd_64 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;

    exitcond6_fu_270_p2 <= "1" when (j_reg_126 = ap_const_lv2_3) else "0";
    exitcond_fu_206_p2 <= "1" when (i_reg_114 = ap_const_lv2_3) else "0";
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_start <= grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_start_ap_start_reg;
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_cols <= p_src_cols_V_read;
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_0_0_V_read <= kernel_val_0_0_V_fu_54;
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_0_1_V_read <= kernel_val_0_1_V_fu_58;
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_0_2_V_read <= kernel_val_0_2_V_1_fu_62;
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_1_0_V_read <= kernel_val_1_0_V_fu_66;
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_1_1_V_read <= kernel_val_1_1_V_fu_70;
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_1_2_V_read <= kernel_val_1_2_V_fu_74;
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_2_0_V_read <= kernel_val_2_0_V_fu_78;
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_2_1_V_read <= kernel_val_2_1_V_fu_82;
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_2_2_V_read <= kernel_val_2_2_V_1_fu_86;
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_0_V_full_n <= p_dst_data_stream_0_V_full_n;
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_1_V_full_n <= p_dst_data_stream_1_V_full_n;
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_2_V_full_n <= p_dst_data_stream_2_V_full_n;
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_0_V_dout <= p_src_data_stream_0_V_dout;
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_0_V_empty_n <= p_src_data_stream_0_V_empty_n;
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_1_V_dout <= p_src_data_stream_1_V_dout;
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_1_V_empty_n <= p_src_data_stream_1_V_empty_n;
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_2_V_dout <= p_src_data_stream_2_V_dout;
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_2_V_empty_n <= p_src_data_stream_2_V_empty_n;
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_rows <= p_src_rows_V_read;
    i_1_fu_212_p2 <= std_logic_vector(unsigned(i_reg_114) + unsigned(ap_const_lv2_1));
    i_cast_fu_202_p1 <= std_logic_vector(resize(unsigned(i_reg_114),5));
    j_1_fu_276_p2 <= std_logic_vector(unsigned(j_reg_126) + unsigned(ap_const_lv2_1));
    j_cast_fu_266_p1 <= std_logic_vector(resize(unsigned(j_reg_126),5));
    kernel_val_0_2_V_fu_517_p3 <= 
        newSel39_fu_509_p3 when (or_cond13_fu_401_p2(0) = '1') else 
        kernel_val_0_2_V_1_fu_62;
    
    a_load_reg_769_temp <= signed(a_load_reg_769);
    kernel_val_2_0_V_3_fu_384_p1 <= std_logic_vector(resize(a_load_reg_769_temp,8));

    kernel_val_2_2_V_10_fu_429_p3 <= 
        newSel22_fu_421_p3 when (or_cond11_fu_395_p2(0) = '1') else 
        kernel_val_2_1_V_fu_82;
    kernel_val_2_2_V_11_fu_437_p1 <= kernel_val_2_0_V_3_fu_384_p1;
    kernel_val_2_2_V_11_fu_437_p3 <= 
        kernel_val_2_2_V_11_fu_437_p1 when (sel_tmp48_reg_797(0) = '1') else 
        kernel_val_2_0_V_fu_78;
    kernel_val_2_2_V_12_fu_458_p3 <= 
        kernel_val_1_2_V_fu_74 when (or_cond11_fu_395_p2(0) = '1') else 
        newSel34_fu_451_p3;
    kernel_val_2_2_V_13_fu_473_p3 <= 
        kernel_val_1_1_V_fu_70 when (or_cond11_fu_395_p2(0) = '1') else 
        newSel36_fu_466_p3;
    kernel_val_2_2_V_14_fu_488_p3 <= 
        kernel_val_1_0_V_fu_66 when (sel_tmp48_reg_797(0) = '1') else 
        kernel_val_2_2_V_6_fu_481_p3;
    kernel_val_2_2_V_15_fu_539_p3 <= 
        kernel_val_0_1_V_fu_58 when (or_cond11_fu_395_p2(0) = '1') else 
        newSel40_fu_532_p3;
    kernel_val_2_2_V_16_fu_554_p3 <= 
        kernel_val_0_0_V_fu_54 when (or_cond_fu_387_p2(0) = '1') else 
        newSel41_fu_547_p3;
    kernel_val_2_2_V_6_fu_481_p1 <= kernel_val_2_0_V_3_fu_384_p1;
    kernel_val_2_2_V_6_fu_481_p3 <= 
        kernel_val_2_2_V_6_fu_481_p1 when (sel_tmp40_reg_791(0) = '1') else 
        kernel_val_1_0_V_fu_66;
    kernel_val_2_2_V_fu_406_p2 <= kernel_val_2_0_V_3_fu_384_p1;
    kernel_val_2_2_V_fu_406_p3 <= 
        kernel_val_2_2_V_1_fu_86 when (or_cond13_fu_401_p2(0) = '1') else 
        kernel_val_2_2_V_fu_406_p2;
    newSel20_fu_414_p2 <= kernel_val_2_0_V_3_fu_384_p1;
    newSel20_fu_414_p3 <= 
        kernel_val_2_1_V_fu_82 when (tmp_99_reg_762(0) = '1') else 
        newSel20_fu_414_p2;
    newSel22_fu_421_p3 <= 
        kernel_val_2_1_V_fu_82 when (or_cond_fu_387_p2(0) = '1') else 
        newSel20_fu_414_p3;
    newSel30_fu_444_p2 <= kernel_val_2_0_V_3_fu_384_p1;
    newSel30_fu_444_p3 <= 
        kernel_val_1_2_V_fu_74 when (sel_tmp24_reg_780(0) = '1') else 
        newSel30_fu_444_p2;
    newSel34_fu_451_p3 <= 
        newSel30_fu_444_p3 when (or_cond7_reg_804(0) = '1') else 
        kernel_val_1_2_V_fu_74;
    newSel36_fu_466_p1 <= kernel_val_2_0_V_3_fu_384_p1;
    newSel36_fu_466_p3 <= 
        newSel36_fu_466_p1 when (sel_tmp24_reg_780(0) = '1') else 
        kernel_val_1_1_V_fu_70;
    newSel37_fu_495_p2 <= kernel_val_2_0_V_3_fu_384_p1;
    newSel37_fu_495_p3 <= 
        kernel_val_0_2_V_1_fu_62 when (sel_tmp12_reg_774(0) = '1') else 
        newSel37_fu_495_p2;
    newSel38_fu_502_p3 <= 
        kernel_val_0_2_V_1_fu_62 when (or_cond7_reg_804(0) = '1') else 
        newSel37_fu_495_p3;
    newSel39_fu_509_p3 <= 
        kernel_val_0_2_V_1_fu_62 when (or_cond11_fu_395_p2(0) = '1') else 
        newSel38_fu_502_p3;
    newSel40_fu_532_p3 <= 
        kernel_val_0_1_V_fu_58 when (or_cond7_reg_804(0) = '1') else 
        newSel_fu_525_p3;
    newSel41_fu_547_p1 <= kernel_val_2_0_V_3_fu_384_p1;
    newSel41_fu_547_p3 <= 
        newSel41_fu_547_p1 when (tmp_99_reg_762(0) = '1') else 
        kernel_val_0_0_V_fu_54;
    newSel_fu_525_p1 <= kernel_val_2_0_V_3_fu_384_p1;
    newSel_fu_525_p3 <= 
        newSel_fu_525_p1 when (sel_tmp12_reg_774(0) = '1') else 
        kernel_val_0_1_V_fu_58;
    or_cond11_fu_395_p2 <= (or_cond_fu_387_p2 or or_cond5_fu_391_p2);
    or_cond12_fu_378_p2 <= (tmp3_fu_363_p2 and tmp5_fu_374_p2);
    or_cond13_fu_401_p2 <= (or_cond11_fu_395_p2 or or_cond12_reg_811);
    or_cond5_fu_391_p2 <= (tmp_99_reg_762 or sel_tmp32_reg_786);
    or_cond7_fu_369_p2 <= (sel_tmp14_reg_690 and tmp3_fu_363_p2);
    or_cond_fu_387_p2 <= (sel_tmp48_reg_797 or sel_tmp40_reg_791);
    p_dst_data_stream_0_V_din <= grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_0_V_din;

    -- p_dst_data_stream_0_V_write assign process. --
    p_dst_data_stream_0_V_write_assign_proc : process(ap_CS_fsm, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_0_V_write)
    begin
        if (((ap_ST_st2_fsm_1 = ap_CS_fsm) or (ap_ST_st6_fsm_5 = ap_CS_fsm))) then 
            p_dst_data_stream_0_V_write <= grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_0_V_write;
        else 
            p_dst_data_stream_0_V_write <= ap_const_logic_0;
        end if; 
    end process;

    p_dst_data_stream_1_V_din <= grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_1_V_din;

    -- p_dst_data_stream_1_V_write assign process. --
    p_dst_data_stream_1_V_write_assign_proc : process(ap_CS_fsm, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_1_V_write)
    begin
        if (((ap_ST_st2_fsm_1 = ap_CS_fsm) or (ap_ST_st6_fsm_5 = ap_CS_fsm))) then 
            p_dst_data_stream_1_V_write <= grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_1_V_write;
        else 
            p_dst_data_stream_1_V_write <= ap_const_logic_0;
        end if; 
    end process;

    p_dst_data_stream_2_V_din <= grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_2_V_din;

    -- p_dst_data_stream_2_V_write assign process. --
    p_dst_data_stream_2_V_write_assign_proc : process(ap_CS_fsm, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_2_V_write)
    begin
        if (((ap_ST_st2_fsm_1 = ap_CS_fsm) or (ap_ST_st6_fsm_5 = ap_CS_fsm))) then 
            p_dst_data_stream_2_V_write <= grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_2_V_write;
        else 
            p_dst_data_stream_2_V_write <= ap_const_logic_0;
        end if; 
    end process;

    p_shl_cast_fu_226_p1 <= std_logic_vector(resize(unsigned(p_shl_fu_218_p3),5));
    p_shl_fu_218_p3 <= (i_reg_114 & ap_const_lv2_0);

    -- p_src_data_stream_0_V_read assign process. --
    p_src_data_stream_0_V_read_assign_proc : process(ap_CS_fsm, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_0_V_read)
    begin
        if (((ap_ST_st2_fsm_1 = ap_CS_fsm) or (ap_ST_st6_fsm_5 = ap_CS_fsm))) then 
            p_src_data_stream_0_V_read <= grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_0_V_read;
        else 
            p_src_data_stream_0_V_read <= ap_const_logic_0;
        end if; 
    end process;


    -- p_src_data_stream_1_V_read assign process. --
    p_src_data_stream_1_V_read_assign_proc : process(ap_CS_fsm, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_1_V_read)
    begin
        if (((ap_ST_st2_fsm_1 = ap_CS_fsm) or (ap_ST_st6_fsm_5 = ap_CS_fsm))) then 
            p_src_data_stream_1_V_read <= grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_1_V_read;
        else 
            p_src_data_stream_1_V_read <= ap_const_logic_0;
        end if; 
    end process;


    -- p_src_data_stream_2_V_read assign process. --
    p_src_data_stream_2_V_read_assign_proc : process(ap_CS_fsm, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_2_V_read)
    begin
        if (((ap_ST_st2_fsm_1 = ap_CS_fsm) or (ap_ST_st6_fsm_5 = ap_CS_fsm))) then 
            p_src_data_stream_2_V_read <= grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_2_V_read;
        else 
            p_src_data_stream_2_V_read <= ap_const_logic_0;
        end if; 
    end process;

    sel_tmp11_fu_326_p2 <= "1" when (j_reg_126 = ap_const_lv2_1) else "0";
    sel_tmp12_fu_332_p2 <= (sel_tmp_reg_684 and sel_tmp11_fu_326_p2);
    sel_tmp14_fu_242_p2 <= "1" when (i_reg_114 = ap_const_lv2_1) else "0";
    sel_tmp24_fu_337_p2 <= (sel_tmp14_reg_690 and sel_tmp11_fu_326_p2);
    sel_tmp29_fu_248_p2 <= "0" when (i_reg_114 = ap_const_lv2_0) else "1";
    sel_tmp30_fu_254_p2 <= "0" when (i_reg_114 = ap_const_lv2_1) else "1";
    sel_tmp31_fu_260_p2 <= (sel_tmp29_fu_248_p2 and sel_tmp30_fu_254_p2);
    sel_tmp32_fu_342_p2 <= (sel_tmp31_reg_698 and sel_tmp11_fu_326_p2);
    sel_tmp39_fu_347_p2 <= "1" when (j_reg_126 = ap_const_lv2_0) else "0";
    sel_tmp40_fu_353_p2 <= (sel_tmp14_reg_690 and sel_tmp39_fu_347_p2);
    sel_tmp48_fu_358_p2 <= (sel_tmp31_reg_698 and sel_tmp39_fu_347_p2);
    sel_tmp5_fu_308_p2 <= "0" when (j_reg_126 = ap_const_lv2_0) else "1";
    sel_tmp7_fu_314_p2 <= "0" when (j_reg_126 = ap_const_lv2_1) else "1";
    sel_tmp_fu_236_p2 <= "1" when (i_reg_114 = ap_const_lv2_0) else "0";
    tmp2_fu_320_p2 <= (sel_tmp5_fu_308_p2 and sel_tmp7_fu_314_p2);
    tmp3_fu_363_p2 <= (tmp2_fu_320_p2 or sel_tmp11_fu_326_p2);
    tmp5_fu_374_p2 <= (sel_tmp14_reg_690 or sel_tmp_reg_684);
    
    tmp_s_fu_282_p2_temp <= signed(tmp_s_fu_282_p2);
    tmp_1_fu_291_p0 <= std_logic_vector(resize(tmp_s_fu_282_p2_temp,32));

    tmp_1_fu_291_p1 <= std_logic_vector(resize(unsigned(tmp_1_fu_291_p0),64));
    tmp_98_fu_296_p2 <= (i_reg_114 or j_reg_126);
    tmp_99_fu_302_p2 <= "1" when (tmp_98_fu_296_p2 = ap_const_lv2_0) else "0";
    tmp_fu_230_p2 <= std_logic_vector(unsigned(p_shl_cast_fu_226_p1) - unsigned(i_cast_fu_202_p1));
    tmp_s_fu_282_p2 <= std_logic_vector(unsigned(tmp_reg_679) + unsigned(j_cast_fu_266_p1));
end behav;
