-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2013.2
-- Copyright (C) 2013 Xilinx Inc. All rights reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity SubS_1080_1920_16_unsigned_char_16_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    src_rows_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
    src_cols_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
    src_data_stream_0_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    src_data_stream_0_V_empty_n : IN STD_LOGIC;
    src_data_stream_0_V_read : OUT STD_LOGIC;
    src_data_stream_1_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    src_data_stream_1_V_empty_n : IN STD_LOGIC;
    src_data_stream_1_V_read : OUT STD_LOGIC;
    src_data_stream_2_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    src_data_stream_2_V_empty_n : IN STD_LOGIC;
    src_data_stream_2_V_read : OUT STD_LOGIC;
    dst_rows_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
    dst_cols_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
    dst_data_stream_0_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    dst_data_stream_0_V_full_n : IN STD_LOGIC;
    dst_data_stream_0_V_write : OUT STD_LOGIC;
    dst_data_stream_1_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    dst_data_stream_1_V_full_n : IN STD_LOGIC;
    dst_data_stream_1_V_write : OUT STD_LOGIC;
    dst_data_stream_2_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    dst_data_stream_2_V_full_n : IN STD_LOGIC;
    dst_data_stream_2_V_write : OUT STD_LOGIC );
end;


architecture behav of SubS_1080_1920_16_unsigned_char_16_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_st1_fsm_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_ST_st2_fsm_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_pp0_stg0_fsm_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_ST_st6_fsm_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv9_1CE : STD_LOGIC_VECTOR (8 downto 0) := "111001110";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal t_V_5_reg_148 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_sig_bdd_58 : BOOLEAN;
    signal i_V_fu_165_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal i_V_reg_285 : STD_LOGIC_VECTOR (11 downto 0);
    signal exitcond4_fu_171_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond4_reg_290 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppiten_pp0_it0 : STD_LOGIC := '0';
    signal ap_sig_bdd_82 : BOOLEAN;
    signal ap_reg_ppiten_pp0_it1 : STD_LOGIC := '0';
    signal ap_reg_ppstg_exitcond4_reg_290_pp0_it1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_bdd_96 : BOOLEAN;
    signal ap_reg_ppiten_pp0_it2 : STD_LOGIC := '0';
    signal j_V_fu_176_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_149_reg_299 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_150_reg_304 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_151_reg_309 : STD_LOGIC_VECTOR (7 downto 0);
    signal exitcond_fu_160_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal t_V_reg_137 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp18_cast_i_fu_182_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal v_assign_fu_185_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_fu_191_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_144_fu_199_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_cast_i_fu_212_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal v_assign_3_fu_215_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_145_fu_221_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_146_fu_229_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_cast_i_fu_242_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal v_assign_4_fu_245_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_147_fu_251_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_148_fu_259_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);


begin



    -- the current state (ap_CS_fsm) of the state machine. --
    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_st1_fsm_0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    -- ap_done_reg assign process. --
    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_continue)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_ST_st2_fsm_1 = ap_CS_fsm) and not((ap_const_lv1_0 = exitcond_fu_160_p2)))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it0 assign process. --
    ap_reg_ppiten_pp0_it0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
            else
                if (((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and not(((ap_sig_bdd_82 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_96 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)))) and not((exitcond4_fu_171_p2 = ap_const_lv1_0)))) then 
                    ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
                elsif (((ap_ST_st2_fsm_1 = ap_CS_fsm) and (ap_const_lv1_0 = exitcond_fu_160_p2))) then 
                    ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it1 assign process. --
    ap_reg_ppiten_pp0_it1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
            else
                if (((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and not(((ap_sig_bdd_82 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_96 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)))) and (exitcond4_fu_171_p2 = ap_const_lv1_0))) then 
                    ap_reg_ppiten_pp0_it1 <= ap_const_logic_1;
                elsif ((((ap_ST_st2_fsm_1 = ap_CS_fsm) and (ap_const_lv1_0 = exitcond_fu_160_p2)) or ((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and not(((ap_sig_bdd_82 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_96 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)))) and not((exitcond4_fu_171_p2 = ap_const_lv1_0))))) then 
                    ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it2 assign process. --
    ap_reg_ppiten_pp0_it2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
            else
                if (((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and not(((ap_sig_bdd_82 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_96 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)))))) then 
                    ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
                elsif (((ap_ST_st2_fsm_1 = ap_CS_fsm) and (ap_const_lv1_0 = exitcond_fu_160_p2))) then 
                    ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    -- t_V_5_reg_148 assign process. --
    t_V_5_reg_148_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not(((ap_sig_bdd_82 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_96 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)))) and (exitcond4_fu_171_p2 = ap_const_lv1_0))) then 
                t_V_5_reg_148 <= j_V_fu_176_p2;
            elsif (((ap_ST_st2_fsm_1 = ap_CS_fsm) and (ap_const_lv1_0 = exitcond_fu_160_p2))) then 
                t_V_5_reg_148 <= ap_const_lv12_0;
            end if; 
        end if;
    end process;

    -- t_V_reg_137 assign process. --
    t_V_reg_137_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_ST_st1_fsm_0 = ap_CS_fsm) and not(ap_sig_bdd_58))) then 
                t_V_reg_137 <= ap_const_lv12_0;
            elsif ((ap_ST_st6_fsm_3 = ap_CS_fsm)) then 
                t_V_reg_137 <= i_V_reg_285;
            end if; 
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and not(((ap_sig_bdd_82 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_96 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)))))) then
                ap_reg_ppstg_exitcond4_reg_290_pp0_it1 <= exitcond4_reg_290;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not(((ap_sig_bdd_82 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_96 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)))))) then
                exitcond4_reg_290 <= exitcond4_fu_171_p2;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_ST_st2_fsm_1 = ap_CS_fsm)) then
                i_V_reg_285 <= i_V_fu_165_p2;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and (exitcond4_reg_290 = ap_const_lv1_0) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not(((ap_sig_bdd_82 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_96 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)))))) then
                tmp_149_reg_299 <= src_data_stream_0_V_dout;
                tmp_150_reg_304 <= src_data_stream_1_V_dout;
                tmp_151_reg_309 <= src_data_stream_2_V_dout;
            end if;
        end if;
    end process;

    -- the next state (ap_NS_fsm) of the state machine. --
    ap_NS_fsm_assign_proc : process (ap_CS_fsm , ap_sig_bdd_58 , exitcond4_fu_171_p2 , ap_reg_ppiten_pp0_it0 , ap_sig_bdd_82 , ap_reg_ppiten_pp0_it1 , ap_sig_bdd_96 , ap_reg_ppiten_pp0_it2 , exitcond_fu_160_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_st1_fsm_0 => 
                if (not(ap_sig_bdd_58)) then
                    ap_NS_fsm <= ap_ST_st2_fsm_1;
                else
                    ap_NS_fsm <= ap_ST_st1_fsm_0;
                end if;
            when ap_ST_st2_fsm_1 => 
                if (not((ap_const_lv1_0 = exitcond_fu_160_p2))) then
                    ap_NS_fsm <= ap_ST_st1_fsm_0;
                else
                    ap_NS_fsm <= ap_ST_pp0_stg0_fsm_2;
                end if;
            when ap_ST_pp0_stg0_fsm_2 => 
                if ((not(((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_82 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_96 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)))) and not((ap_const_logic_1 = ap_reg_ppiten_pp0_it1)))) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not(((ap_sig_bdd_82 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_96 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)))) and not((exitcond4_fu_171_p2 = ap_const_lv1_0)) and not((ap_const_logic_1 = ap_reg_ppiten_pp0_it1)))))) then
                    ap_NS_fsm <= ap_ST_pp0_stg0_fsm_2;
                elsif ((((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_82 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_96 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)))) and not((ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not(((ap_sig_bdd_82 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_96 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)))) and not((exitcond4_fu_171_p2 = ap_const_lv1_0)) and not((ap_const_logic_1 = ap_reg_ppiten_pp0_it1))))) then
                    ap_NS_fsm <= ap_ST_st6_fsm_3;
                else
                    ap_NS_fsm <= ap_ST_pp0_stg0_fsm_2;
                end if;
            when ap_ST_st6_fsm_3 => 
                ap_NS_fsm <= ap_ST_st2_fsm_1;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;

    -- ap_done assign process. --
    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm, exitcond_fu_160_p2)
    begin
        if (((ap_const_logic_1 = ap_done_reg) or ((ap_ST_st2_fsm_1 = ap_CS_fsm) and not((ap_const_lv1_0 = exitcond_fu_160_p2))))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_idle assign process. --
    ap_idle_assign_proc : process(ap_start, ap_CS_fsm)
    begin
        if ((not((ap_const_logic_1 = ap_start)) and (ap_ST_st1_fsm_0 = ap_CS_fsm))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_ready assign process. --
    ap_ready_assign_proc : process(ap_CS_fsm, exitcond_fu_160_p2)
    begin
        if (((ap_ST_st2_fsm_1 = ap_CS_fsm) and not((ap_const_lv1_0 = exitcond_fu_160_p2)))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_bdd_58 assign process. --
    ap_sig_bdd_58_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_sig_bdd_58 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    -- ap_sig_bdd_82 assign process. --
    ap_sig_bdd_82_assign_proc : process(src_data_stream_0_V_empty_n, src_data_stream_1_V_empty_n, src_data_stream_2_V_empty_n, exitcond4_reg_290)
    begin
                ap_sig_bdd_82 <= (((src_data_stream_0_V_empty_n = ap_const_logic_0) and (exitcond4_reg_290 = ap_const_lv1_0)) or ((exitcond4_reg_290 = ap_const_lv1_0) and (src_data_stream_1_V_empty_n = ap_const_logic_0)) or ((exitcond4_reg_290 = ap_const_lv1_0) and (src_data_stream_2_V_empty_n = ap_const_logic_0)));
    end process;


    -- ap_sig_bdd_96 assign process. --
    ap_sig_bdd_96_assign_proc : process(dst_data_stream_0_V_full_n, dst_data_stream_1_V_full_n, dst_data_stream_2_V_full_n, ap_reg_ppstg_exitcond4_reg_290_pp0_it1)
    begin
                ap_sig_bdd_96 <= (((dst_data_stream_0_V_full_n = ap_const_logic_0) and (ap_const_lv1_0 = ap_reg_ppstg_exitcond4_reg_290_pp0_it1)) or ((ap_const_lv1_0 = ap_reg_ppstg_exitcond4_reg_290_pp0_it1) and (dst_data_stream_1_V_full_n = ap_const_logic_0)) or ((ap_const_lv1_0 = ap_reg_ppstg_exitcond4_reg_290_pp0_it1) and (dst_data_stream_2_V_full_n = ap_const_logic_0)));
    end process;

    dst_data_stream_0_V_din <= 
        ap_const_lv8_0 when (tmp_fu_191_p3(0) = '1') else 
        tmp_144_fu_199_p1;

    -- dst_data_stream_0_V_write assign process. --
    dst_data_stream_0_V_write_assign_proc : process(ap_CS_fsm, ap_sig_bdd_82, ap_reg_ppiten_pp0_it1, ap_reg_ppstg_exitcond4_reg_290_pp0_it1, ap_sig_bdd_96, ap_reg_ppiten_pp0_it2)
    begin
        if (((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and (ap_const_lv1_0 = ap_reg_ppstg_exitcond4_reg_290_pp0_it1) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_82 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_96 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)))))) then 
            dst_data_stream_0_V_write <= ap_const_logic_1;
        else 
            dst_data_stream_0_V_write <= ap_const_logic_0;
        end if; 
    end process;

    dst_data_stream_1_V_din <= 
        ap_const_lv8_0 when (tmp_145_fu_221_p3(0) = '1') else 
        tmp_146_fu_229_p1;

    -- dst_data_stream_1_V_write assign process. --
    dst_data_stream_1_V_write_assign_proc : process(ap_CS_fsm, ap_sig_bdd_82, ap_reg_ppiten_pp0_it1, ap_reg_ppstg_exitcond4_reg_290_pp0_it1, ap_sig_bdd_96, ap_reg_ppiten_pp0_it2)
    begin
        if (((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and (ap_const_lv1_0 = ap_reg_ppstg_exitcond4_reg_290_pp0_it1) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_82 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_96 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)))))) then 
            dst_data_stream_1_V_write <= ap_const_logic_1;
        else 
            dst_data_stream_1_V_write <= ap_const_logic_0;
        end if; 
    end process;

    dst_data_stream_2_V_din <= 
        ap_const_lv8_0 when (tmp_147_fu_251_p3(0) = '1') else 
        tmp_148_fu_259_p1;

    -- dst_data_stream_2_V_write assign process. --
    dst_data_stream_2_V_write_assign_proc : process(ap_CS_fsm, ap_sig_bdd_82, ap_reg_ppiten_pp0_it1, ap_reg_ppstg_exitcond4_reg_290_pp0_it1, ap_sig_bdd_96, ap_reg_ppiten_pp0_it2)
    begin
        if (((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and (ap_const_lv1_0 = ap_reg_ppstg_exitcond4_reg_290_pp0_it1) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_82 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_96 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)))))) then 
            dst_data_stream_2_V_write <= ap_const_logic_1;
        else 
            dst_data_stream_2_V_write <= ap_const_logic_0;
        end if; 
    end process;

    exitcond4_fu_171_p2 <= "1" when (t_V_5_reg_148 = dst_cols_V_read) else "0";
    exitcond_fu_160_p2 <= "1" when (t_V_reg_137 = dst_rows_V_read) else "0";
    i_V_fu_165_p2 <= std_logic_vector(unsigned(t_V_reg_137) + unsigned(ap_const_lv12_1));
    j_V_fu_176_p2 <= std_logic_vector(unsigned(t_V_5_reg_148) + unsigned(ap_const_lv12_1));

    -- src_data_stream_0_V_read assign process. --
    src_data_stream_0_V_read_assign_proc : process(ap_CS_fsm, exitcond4_reg_290, ap_sig_bdd_82, ap_reg_ppiten_pp0_it1, ap_sig_bdd_96, ap_reg_ppiten_pp0_it2)
    begin
        if (((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and (exitcond4_reg_290 = ap_const_lv1_0) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not(((ap_sig_bdd_82 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_96 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)))))) then 
            src_data_stream_0_V_read <= ap_const_logic_1;
        else 
            src_data_stream_0_V_read <= ap_const_logic_0;
        end if; 
    end process;


    -- src_data_stream_1_V_read assign process. --
    src_data_stream_1_V_read_assign_proc : process(ap_CS_fsm, exitcond4_reg_290, ap_sig_bdd_82, ap_reg_ppiten_pp0_it1, ap_sig_bdd_96, ap_reg_ppiten_pp0_it2)
    begin
        if (((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and (exitcond4_reg_290 = ap_const_lv1_0) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not(((ap_sig_bdd_82 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_96 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)))))) then 
            src_data_stream_1_V_read <= ap_const_logic_1;
        else 
            src_data_stream_1_V_read <= ap_const_logic_0;
        end if; 
    end process;


    -- src_data_stream_2_V_read assign process. --
    src_data_stream_2_V_read_assign_proc : process(ap_CS_fsm, exitcond4_reg_290, ap_sig_bdd_82, ap_reg_ppiten_pp0_it1, ap_sig_bdd_96, ap_reg_ppiten_pp0_it2)
    begin
        if (((ap_ST_pp0_stg0_fsm_2 = ap_CS_fsm) and (exitcond4_reg_290 = ap_const_lv1_0) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not(((ap_sig_bdd_82 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)) or (ap_sig_bdd_96 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)))))) then 
            src_data_stream_2_V_read <= ap_const_logic_1;
        else 
            src_data_stream_2_V_read <= ap_const_logic_0;
        end if; 
    end process;

    tmp18_cast_i_fu_182_p1 <= std_logic_vector(resize(unsigned(tmp_149_reg_299),9));
    tmp_144_fu_199_p1 <= v_assign_fu_185_p2(8 - 1 downto 0);
    tmp_145_fu_221_p3 <= v_assign_3_fu_215_p2(8 downto 8);
    tmp_146_fu_229_p1 <= v_assign_3_fu_215_p2(8 - 1 downto 0);
    tmp_147_fu_251_p3 <= v_assign_4_fu_245_p2(8 downto 8);
    tmp_148_fu_259_p1 <= v_assign_4_fu_245_p2(8 - 1 downto 0);
    tmp_1_cast_i_fu_212_p1 <= std_logic_vector(resize(unsigned(tmp_150_reg_304),9));
    tmp_2_cast_i_fu_242_p1 <= std_logic_vector(resize(unsigned(tmp_151_reg_309),9));
    tmp_fu_191_p3 <= v_assign_fu_185_p2(8 downto 8);
    v_assign_3_fu_215_p2 <= std_logic_vector(unsigned(tmp_1_cast_i_fu_212_p1) + unsigned(ap_const_lv9_1CE));
    v_assign_4_fu_245_p2 <= std_logic_vector(unsigned(tmp_2_cast_i_fu_242_p1) + unsigned(ap_const_lv9_1CE));
    v_assign_fu_185_p2 <= std_logic_vector(unsigned(tmp18_cast_i_fu_182_p1) + unsigned(ap_const_lv9_1CE));
end behav;
