// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.2
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _Erode_16_16_1080_1920_s_HH_
#define _Erode_16_16_1080_1920_s_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s.h"
#include "getStructuringElement_unsigned_char_int_int_3_3_s.h"

namespace ap_rtl {

struct Erode_16_16_1080_1920_s : public sc_module {
    // Port declarations 27
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<12> > p_src_rows_V_read;
    sc_in< sc_lv<12> > p_src_cols_V_read;
    sc_in< sc_lv<8> > p_src_data_stream_0_V_dout;
    sc_in< sc_logic > p_src_data_stream_0_V_empty_n;
    sc_out< sc_logic > p_src_data_stream_0_V_read;
    sc_in< sc_lv<8> > p_src_data_stream_1_V_dout;
    sc_in< sc_logic > p_src_data_stream_1_V_empty_n;
    sc_out< sc_logic > p_src_data_stream_1_V_read;
    sc_in< sc_lv<8> > p_src_data_stream_2_V_dout;
    sc_in< sc_logic > p_src_data_stream_2_V_empty_n;
    sc_out< sc_logic > p_src_data_stream_2_V_read;
    sc_out< sc_lv<8> > p_dst_data_stream_0_V_din;
    sc_in< sc_logic > p_dst_data_stream_0_V_full_n;
    sc_out< sc_logic > p_dst_data_stream_0_V_write;
    sc_out< sc_lv<8> > p_dst_data_stream_1_V_din;
    sc_in< sc_logic > p_dst_data_stream_1_V_full_n;
    sc_out< sc_logic > p_dst_data_stream_1_V_write;
    sc_out< sc_lv<8> > p_dst_data_stream_2_V_din;
    sc_in< sc_logic > p_dst_data_stream_2_V_full_n;
    sc_out< sc_logic > p_dst_data_stream_2_V_write;


    // Module declarations
    Erode_16_16_1080_1920_s(sc_module_name name);
    SC_HAS_PROCESS(Erode_16_16_1080_1920_s);

    ~Erode_16_16_1080_1920_s();

    sc_trace_file* mVcdFile;

    filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s* grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51;
    getStructuringElement_unsigned_char_int_int_3_3_s* grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_80;
    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<2> > ap_CS_fsm;
    sc_signal< sc_logic > grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_80_ap_done;
    sc_signal< sc_lv<8> > temp_kernel_val_0_0_reg_139;
    sc_signal< sc_lv<8> > temp_kernel_val_0_1_reg_144;
    sc_signal< sc_lv<8> > temp_kernel_val_0_2_reg_149;
    sc_signal< sc_lv<8> > temp_kernel_val_1_0_reg_154;
    sc_signal< sc_lv<8> > temp_kernel_val_1_1_reg_159;
    sc_signal< sc_lv<8> > temp_kernel_val_1_2_reg_164;
    sc_signal< sc_lv<8> > temp_kernel_val_2_0_reg_169;
    sc_signal< sc_lv<8> > temp_kernel_val_2_1_reg_174;
    sc_signal< sc_lv<8> > temp_kernel_val_2_2_reg_179;
    sc_signal< sc_logic > grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_ap_start;
    sc_signal< sc_logic > grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_ap_done;
    sc_signal< sc_logic > grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_ap_idle;
    sc_signal< sc_logic > grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_ap_ready;
    sc_signal< sc_lv<8> > grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_p_src_data_stream_0_V_dout;
    sc_signal< sc_logic > grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_p_src_data_stream_0_V_empty_n;
    sc_signal< sc_logic > grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_p_src_data_stream_0_V_read;
    sc_signal< sc_lv<8> > grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_p_src_data_stream_1_V_dout;
    sc_signal< sc_logic > grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_p_src_data_stream_1_V_empty_n;
    sc_signal< sc_logic > grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_p_src_data_stream_1_V_read;
    sc_signal< sc_lv<8> > grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_p_src_data_stream_2_V_dout;
    sc_signal< sc_logic > grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_p_src_data_stream_2_V_empty_n;
    sc_signal< sc_logic > grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_p_src_data_stream_2_V_read;
    sc_signal< sc_lv<8> > grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_p_dst_data_stream_0_V_din;
    sc_signal< sc_logic > grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_p_dst_data_stream_0_V_full_n;
    sc_signal< sc_logic > grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_p_dst_data_stream_0_V_write;
    sc_signal< sc_lv<8> > grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_p_dst_data_stream_1_V_din;
    sc_signal< sc_logic > grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_p_dst_data_stream_1_V_full_n;
    sc_signal< sc_logic > grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_p_dst_data_stream_1_V_write;
    sc_signal< sc_lv<8> > grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_p_dst_data_stream_2_V_din;
    sc_signal< sc_logic > grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_p_dst_data_stream_2_V_full_n;
    sc_signal< sc_logic > grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_p_dst_data_stream_2_V_write;
    sc_signal< sc_lv<8> > grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_kernel_val_0_0_read;
    sc_signal< sc_lv<8> > grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_kernel_val_0_1_read;
    sc_signal< sc_lv<8> > grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_kernel_val_0_2_read;
    sc_signal< sc_lv<8> > grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_kernel_val_1_0_read;
    sc_signal< sc_lv<8> > grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_kernel_val_1_1_read;
    sc_signal< sc_lv<8> > grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_kernel_val_1_2_read;
    sc_signal< sc_lv<8> > grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_kernel_val_2_0_read;
    sc_signal< sc_lv<8> > grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_kernel_val_2_1_read;
    sc_signal< sc_lv<8> > grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_kernel_val_2_2_read;
    sc_signal< sc_lv<12> > grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_rows;
    sc_signal< sc_lv<12> > grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_cols;
    sc_signal< sc_logic > grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_80_ap_start;
    sc_signal< sc_logic > grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_80_ap_idle;
    sc_signal< sc_logic > grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_80_ap_ready;
    sc_signal< sc_lv<8> > grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_80_ap_return_0;
    sc_signal< sc_lv<8> > grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_80_ap_return_1;
    sc_signal< sc_lv<8> > grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_80_ap_return_2;
    sc_signal< sc_lv<8> > grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_80_ap_return_3;
    sc_signal< sc_lv<8> > grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_80_ap_return_4;
    sc_signal< sc_lv<8> > grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_80_ap_return_5;
    sc_signal< sc_lv<8> > grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_80_ap_return_6;
    sc_signal< sc_lv<8> > grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_80_ap_return_7;
    sc_signal< sc_lv<8> > grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_80_ap_return_8;
    sc_signal< sc_logic > grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_ap_start_ap_start_reg;
    sc_signal< sc_logic > grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_80_ap_start_ap_start_reg;
    sc_signal< bool > ap_sig_bdd_133;
    sc_signal< sc_lv<2> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<2> ap_ST_st1_fsm_0;
    static const sc_lv<2> ap_ST_st2_fsm_1;
    static const sc_lv<2> ap_ST_st3_fsm_2;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sig_bdd_133();
    void thread_grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_ap_start();
    void thread_grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_cols();
    void thread_grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_kernel_val_0_0_read();
    void thread_grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_kernel_val_0_1_read();
    void thread_grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_kernel_val_0_2_read();
    void thread_grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_kernel_val_1_0_read();
    void thread_grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_kernel_val_1_1_read();
    void thread_grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_kernel_val_1_2_read();
    void thread_grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_kernel_val_2_0_read();
    void thread_grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_kernel_val_2_1_read();
    void thread_grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_kernel_val_2_2_read();
    void thread_grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_p_dst_data_stream_0_V_full_n();
    void thread_grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_p_dst_data_stream_1_V_full_n();
    void thread_grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_p_dst_data_stream_2_V_full_n();
    void thread_grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_p_src_data_stream_0_V_dout();
    void thread_grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_p_src_data_stream_0_V_empty_n();
    void thread_grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_p_src_data_stream_1_V_dout();
    void thread_grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_p_src_data_stream_1_V_empty_n();
    void thread_grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_p_src_data_stream_2_V_dout();
    void thread_grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_p_src_data_stream_2_V_empty_n();
    void thread_grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_51_rows();
    void thread_grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_80_ap_start();
    void thread_p_dst_data_stream_0_V_din();
    void thread_p_dst_data_stream_0_V_write();
    void thread_p_dst_data_stream_1_V_din();
    void thread_p_dst_data_stream_1_V_write();
    void thread_p_dst_data_stream_2_V_din();
    void thread_p_dst_data_stream_2_V_write();
    void thread_p_src_data_stream_0_V_read();
    void thread_p_src_data_stream_1_V_read();
    void thread_p_src_data_stream_2_V_read();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
