// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.2
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "Sobel_1_0_3_16_16_1080_1920_1080_1920_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic Sobel_1_0_3_16_16_1080_1920_1080_1920_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic Sobel_1_0_3_16_16_1080_1920_1080_1920_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> Sobel_1_0_3_16_16_1080_1920_1080_1920_s::ap_ST_st1_fsm_0 = "000";
const sc_lv<3> Sobel_1_0_3_16_16_1080_1920_1080_1920_s::ap_ST_st2_fsm_1 = "1";
const sc_lv<3> Sobel_1_0_3_16_16_1080_1920_1080_1920_s::ap_ST_st3_fsm_2 = "10";
const sc_lv<3> Sobel_1_0_3_16_16_1080_1920_1080_1920_s::ap_ST_st4_fsm_3 = "11";
const sc_lv<3> Sobel_1_0_3_16_16_1080_1920_1080_1920_s::ap_ST_st5_fsm_4 = "100";
const sc_lv<3> Sobel_1_0_3_16_16_1080_1920_1080_1920_s::ap_ST_st6_fsm_5 = "101";
const sc_lv<1> Sobel_1_0_3_16_16_1080_1920_1080_1920_s::ap_const_lv1_0 = "0";
const sc_lv<2> Sobel_1_0_3_16_16_1080_1920_1080_1920_s::ap_const_lv2_0 = "00";
const sc_lv<2> Sobel_1_0_3_16_16_1080_1920_1080_1920_s::ap_const_lv2_3 = "11";
const sc_lv<2> Sobel_1_0_3_16_16_1080_1920_1080_1920_s::ap_const_lv2_1 = "1";

Sobel_1_0_3_16_16_1080_1920_1080_1920_s::Sobel_1_0_3_16_16_1080_1920_1080_1920_s(sc_module_name name) : sc_module(name), mVcdFile(0) {
    a_U = new Sobel_1_0_3_16_16_1080_1920_1080_1920_s_a("a_U");
    a_U->clk(ap_clk);
    a_U->reset(ap_rst);
    a_U->address0(a_address0);
    a_U->ce0(a_ce0);
    a_U->q0(a_q0);
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139 = new filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s("grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139");
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139->ap_clk(ap_clk);
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139->ap_rst(ap_rst);
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139->ap_start(grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_start);
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139->ap_done(grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_done);
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139->ap_idle(grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_idle);
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139->ap_ready(grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_ready);
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139->p_src_data_stream_0_V_dout(grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_0_V_dout);
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139->p_src_data_stream_0_V_empty_n(grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_0_V_empty_n);
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139->p_src_data_stream_0_V_read(grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_0_V_read);
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139->p_src_data_stream_1_V_dout(grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_1_V_dout);
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139->p_src_data_stream_1_V_empty_n(grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_1_V_empty_n);
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139->p_src_data_stream_1_V_read(grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_1_V_read);
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139->p_src_data_stream_2_V_dout(grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_2_V_dout);
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139->p_src_data_stream_2_V_empty_n(grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_2_V_empty_n);
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139->p_src_data_stream_2_V_read(grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_2_V_read);
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139->p_dst_data_stream_0_V_din(grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_0_V_din);
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139->p_dst_data_stream_0_V_full_n(grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_0_V_full_n);
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139->p_dst_data_stream_0_V_write(grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_0_V_write);
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139->p_dst_data_stream_1_V_din(grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_1_V_din);
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139->p_dst_data_stream_1_V_full_n(grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_1_V_full_n);
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139->p_dst_data_stream_1_V_write(grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_1_V_write);
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139->p_dst_data_stream_2_V_din(grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_2_V_din);
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139->p_dst_data_stream_2_V_full_n(grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_2_V_full_n);
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139->p_dst_data_stream_2_V_write(grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_2_V_write);
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139->kernel_val_0_0_V_read(grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_0_0_V_read);
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139->kernel_val_0_1_V_read(grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_0_1_V_read);
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139->kernel_val_0_2_V_read(grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_0_2_V_read);
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139->kernel_val_1_0_V_read(grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_1_0_V_read);
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139->kernel_val_1_1_V_read(grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_1_1_V_read);
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139->kernel_val_1_2_V_read(grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_1_2_V_read);
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139->kernel_val_2_0_V_read(grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_2_0_V_read);
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139->kernel_val_2_1_V_read(grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_2_1_V_read);
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139->kernel_val_2_2_V_read(grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_2_2_V_read);
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139->rows(grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_rows);
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139->cols(grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_cols);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_a_address0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_1_fu_291_p1 );

    SC_METHOD(thread_a_ce0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond6_fu_270_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_done );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_done );

    SC_METHOD(thread_ap_sig_bdd_64);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_exitcond6_fu_270_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( j_reg_126 );

    SC_METHOD(thread_exitcond_fu_206_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( i_reg_114 );

    SC_METHOD(thread_grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_start);
    sensitive << ( grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_start_ap_start_reg );

    SC_METHOD(thread_grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_cols);
    sensitive << ( ap_CS_fsm );
    sensitive << ( p_src_cols_V_read );

    SC_METHOD(thread_grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_0_0_V_read);
    sensitive << ( ap_CS_fsm );
    sensitive << ( kernel_val_0_0_V_fu_54 );

    SC_METHOD(thread_grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_0_1_V_read);
    sensitive << ( ap_CS_fsm );
    sensitive << ( kernel_val_0_1_V_fu_58 );

    SC_METHOD(thread_grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_0_2_V_read);
    sensitive << ( ap_CS_fsm );
    sensitive << ( kernel_val_0_2_V_1_fu_62 );

    SC_METHOD(thread_grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_1_0_V_read);
    sensitive << ( ap_CS_fsm );
    sensitive << ( kernel_val_1_0_V_fu_66 );

    SC_METHOD(thread_grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_1_1_V_read);
    sensitive << ( ap_CS_fsm );
    sensitive << ( kernel_val_1_1_V_fu_70 );

    SC_METHOD(thread_grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_1_2_V_read);
    sensitive << ( ap_CS_fsm );
    sensitive << ( kernel_val_1_2_V_fu_74 );

    SC_METHOD(thread_grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_2_0_V_read);
    sensitive << ( ap_CS_fsm );
    sensitive << ( kernel_val_2_0_V_fu_78 );

    SC_METHOD(thread_grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_2_1_V_read);
    sensitive << ( ap_CS_fsm );
    sensitive << ( kernel_val_2_1_V_fu_82 );

    SC_METHOD(thread_grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_2_2_V_read);
    sensitive << ( ap_CS_fsm );
    sensitive << ( kernel_val_2_2_V_1_fu_86 );

    SC_METHOD(thread_grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_0_V_full_n);
    sensitive << ( ap_CS_fsm );
    sensitive << ( p_dst_data_stream_0_V_full_n );

    SC_METHOD(thread_grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_1_V_full_n);
    sensitive << ( ap_CS_fsm );
    sensitive << ( p_dst_data_stream_1_V_full_n );

    SC_METHOD(thread_grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_2_V_full_n);
    sensitive << ( ap_CS_fsm );
    sensitive << ( p_dst_data_stream_2_V_full_n );

    SC_METHOD(thread_grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_0_V_dout);
    sensitive << ( ap_CS_fsm );
    sensitive << ( p_src_data_stream_0_V_dout );
    sensitive << ( exitcond_fu_206_p2 );

    SC_METHOD(thread_grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_0_V_empty_n);
    sensitive << ( ap_CS_fsm );
    sensitive << ( p_src_data_stream_0_V_empty_n );

    SC_METHOD(thread_grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_1_V_dout);
    sensitive << ( ap_CS_fsm );
    sensitive << ( p_src_data_stream_1_V_dout );
    sensitive << ( exitcond_fu_206_p2 );

    SC_METHOD(thread_grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_1_V_empty_n);
    sensitive << ( ap_CS_fsm );
    sensitive << ( p_src_data_stream_1_V_empty_n );

    SC_METHOD(thread_grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_2_V_dout);
    sensitive << ( ap_CS_fsm );
    sensitive << ( p_src_data_stream_2_V_dout );
    sensitive << ( exitcond_fu_206_p2 );

    SC_METHOD(thread_grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_2_V_empty_n);
    sensitive << ( ap_CS_fsm );
    sensitive << ( p_src_data_stream_2_V_empty_n );

    SC_METHOD(thread_grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_rows);
    sensitive << ( ap_CS_fsm );
    sensitive << ( p_src_rows_V_read );

    SC_METHOD(thread_i_1_fu_212_p2);
    sensitive << ( i_reg_114 );

    SC_METHOD(thread_i_cast_fu_202_p1);
    sensitive << ( i_reg_114 );

    SC_METHOD(thread_j_1_fu_276_p2);
    sensitive << ( j_reg_126 );

    SC_METHOD(thread_j_cast_fu_266_p1);
    sensitive << ( j_reg_126 );

    SC_METHOD(thread_kernel_val_0_2_V_fu_517_p3);
    sensitive << ( kernel_val_0_2_V_1_fu_62 );
    sensitive << ( or_cond13_fu_401_p2 );
    sensitive << ( newSel39_fu_509_p3 );

    SC_METHOD(thread_kernel_val_2_0_V_3_fu_384_p1);
    sensitive << ( a_load_reg_769 );

    SC_METHOD(thread_kernel_val_2_2_V_10_fu_429_p3);
    sensitive << ( kernel_val_2_1_V_fu_82 );
    sensitive << ( or_cond11_fu_395_p2 );
    sensitive << ( newSel22_fu_421_p3 );

    SC_METHOD(thread_kernel_val_2_2_V_11_fu_437_p1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( kernel_val_2_0_V_3_fu_384_p1 );

    SC_METHOD(thread_kernel_val_2_2_V_11_fu_437_p3);
    sensitive << ( sel_tmp48_reg_797 );
    sensitive << ( kernel_val_2_0_V_fu_78 );
    sensitive << ( kernel_val_2_2_V_11_fu_437_p1 );

    SC_METHOD(thread_kernel_val_2_2_V_12_fu_458_p3);
    sensitive << ( kernel_val_1_2_V_fu_74 );
    sensitive << ( or_cond11_fu_395_p2 );
    sensitive << ( newSel34_fu_451_p3 );

    SC_METHOD(thread_kernel_val_2_2_V_13_fu_473_p3);
    sensitive << ( kernel_val_1_1_V_fu_70 );
    sensitive << ( or_cond11_fu_395_p2 );
    sensitive << ( newSel36_fu_466_p3 );

    SC_METHOD(thread_kernel_val_2_2_V_14_fu_488_p3);
    sensitive << ( sel_tmp48_reg_797 );
    sensitive << ( kernel_val_1_0_V_fu_66 );
    sensitive << ( kernel_val_2_2_V_6_fu_481_p3 );

    SC_METHOD(thread_kernel_val_2_2_V_15_fu_539_p3);
    sensitive << ( kernel_val_0_1_V_fu_58 );
    sensitive << ( or_cond11_fu_395_p2 );
    sensitive << ( newSel40_fu_532_p3 );

    SC_METHOD(thread_kernel_val_2_2_V_16_fu_554_p3);
    sensitive << ( kernel_val_0_0_V_fu_54 );
    sensitive << ( or_cond_fu_387_p2 );
    sensitive << ( newSel41_fu_547_p3 );

    SC_METHOD(thread_kernel_val_2_2_V_6_fu_481_p1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( sel_tmp48_reg_797 );
    sensitive << ( kernel_val_2_0_V_3_fu_384_p1 );

    SC_METHOD(thread_kernel_val_2_2_V_6_fu_481_p3);
    sensitive << ( sel_tmp40_reg_791 );
    sensitive << ( kernel_val_1_0_V_fu_66 );
    sensitive << ( kernel_val_2_2_V_6_fu_481_p1 );

    SC_METHOD(thread_kernel_val_2_2_V_fu_406_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( kernel_val_2_0_V_3_fu_384_p1 );

    SC_METHOD(thread_kernel_val_2_2_V_fu_406_p3);
    sensitive << ( kernel_val_2_2_V_1_fu_86 );
    sensitive << ( or_cond13_fu_401_p2 );
    sensitive << ( kernel_val_2_2_V_fu_406_p2 );

    SC_METHOD(thread_newSel20_fu_414_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( kernel_val_2_0_V_3_fu_384_p1 );

    SC_METHOD(thread_newSel20_fu_414_p3);
    sensitive << ( tmp_99_reg_762 );
    sensitive << ( kernel_val_2_1_V_fu_82 );
    sensitive << ( newSel20_fu_414_p2 );

    SC_METHOD(thread_newSel22_fu_421_p3);
    sensitive << ( kernel_val_2_1_V_fu_82 );
    sensitive << ( or_cond_fu_387_p2 );
    sensitive << ( newSel20_fu_414_p3 );

    SC_METHOD(thread_newSel30_fu_444_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( or_cond7_reg_804 );
    sensitive << ( kernel_val_2_0_V_3_fu_384_p1 );

    SC_METHOD(thread_newSel30_fu_444_p3);
    sensitive << ( sel_tmp24_reg_780 );
    sensitive << ( kernel_val_1_2_V_fu_74 );
    sensitive << ( newSel30_fu_444_p2 );

    SC_METHOD(thread_newSel34_fu_451_p3);
    sensitive << ( or_cond7_reg_804 );
    sensitive << ( kernel_val_1_2_V_fu_74 );
    sensitive << ( newSel30_fu_444_p3 );

    SC_METHOD(thread_newSel36_fu_466_p1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( kernel_val_2_0_V_3_fu_384_p1 );

    SC_METHOD(thread_newSel36_fu_466_p3);
    sensitive << ( sel_tmp24_reg_780 );
    sensitive << ( kernel_val_1_1_V_fu_70 );
    sensitive << ( newSel36_fu_466_p1 );

    SC_METHOD(thread_newSel37_fu_495_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( or_cond7_reg_804 );
    sensitive << ( kernel_val_2_0_V_3_fu_384_p1 );

    SC_METHOD(thread_newSel37_fu_495_p3);
    sensitive << ( sel_tmp12_reg_774 );
    sensitive << ( kernel_val_0_2_V_1_fu_62 );
    sensitive << ( newSel37_fu_495_p2 );

    SC_METHOD(thread_newSel38_fu_502_p3);
    sensitive << ( or_cond7_reg_804 );
    sensitive << ( kernel_val_0_2_V_1_fu_62 );
    sensitive << ( newSel37_fu_495_p3 );

    SC_METHOD(thread_newSel39_fu_509_p3);
    sensitive << ( kernel_val_0_2_V_1_fu_62 );
    sensitive << ( or_cond11_fu_395_p2 );
    sensitive << ( newSel38_fu_502_p3 );

    SC_METHOD(thread_newSel40_fu_532_p3);
    sensitive << ( or_cond7_reg_804 );
    sensitive << ( kernel_val_0_1_V_fu_58 );
    sensitive << ( newSel_fu_525_p3 );

    SC_METHOD(thread_newSel41_fu_547_p1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( kernel_val_2_0_V_3_fu_384_p1 );

    SC_METHOD(thread_newSel41_fu_547_p3);
    sensitive << ( tmp_99_reg_762 );
    sensitive << ( kernel_val_0_0_V_fu_54 );
    sensitive << ( newSel41_fu_547_p1 );

    SC_METHOD(thread_newSel_fu_525_p1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( or_cond7_reg_804 );
    sensitive << ( kernel_val_2_0_V_3_fu_384_p1 );

    SC_METHOD(thread_newSel_fu_525_p3);
    sensitive << ( sel_tmp12_reg_774 );
    sensitive << ( kernel_val_0_1_V_fu_58 );
    sensitive << ( newSel_fu_525_p1 );

    SC_METHOD(thread_or_cond11_fu_395_p2);
    sensitive << ( or_cond_fu_387_p2 );
    sensitive << ( or_cond5_fu_391_p2 );

    SC_METHOD(thread_or_cond12_fu_378_p2);
    sensitive << ( tmp3_fu_363_p2 );
    sensitive << ( tmp5_fu_374_p2 );

    SC_METHOD(thread_or_cond13_fu_401_p2);
    sensitive << ( or_cond12_reg_811 );
    sensitive << ( or_cond11_fu_395_p2 );

    SC_METHOD(thread_or_cond5_fu_391_p2);
    sensitive << ( tmp_99_reg_762 );
    sensitive << ( sel_tmp32_reg_786 );

    SC_METHOD(thread_or_cond7_fu_369_p2);
    sensitive << ( sel_tmp14_reg_690 );
    sensitive << ( tmp3_fu_363_p2 );

    SC_METHOD(thread_or_cond_fu_387_p2);
    sensitive << ( sel_tmp40_reg_791 );
    sensitive << ( sel_tmp48_reg_797 );

    SC_METHOD(thread_p_dst_data_stream_0_V_din);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_fu_206_p2 );
    sensitive << ( grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_0_V_din );

    SC_METHOD(thread_p_dst_data_stream_0_V_write);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_0_V_write );

    SC_METHOD(thread_p_dst_data_stream_1_V_din);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_fu_206_p2 );
    sensitive << ( grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_1_V_din );

    SC_METHOD(thread_p_dst_data_stream_1_V_write);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_1_V_write );

    SC_METHOD(thread_p_dst_data_stream_2_V_din);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_fu_206_p2 );
    sensitive << ( grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_2_V_din );

    SC_METHOD(thread_p_dst_data_stream_2_V_write);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_2_V_write );

    SC_METHOD(thread_p_shl_cast_fu_226_p1);
    sensitive << ( p_shl_fu_218_p3 );

    SC_METHOD(thread_p_shl_fu_218_p3);
    sensitive << ( i_reg_114 );

    SC_METHOD(thread_p_src_data_stream_0_V_read);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_0_V_read );

    SC_METHOD(thread_p_src_data_stream_1_V_read);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_1_V_read );

    SC_METHOD(thread_p_src_data_stream_2_V_read);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_2_V_read );

    SC_METHOD(thread_sel_tmp11_fu_326_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( j_reg_126 );

    SC_METHOD(thread_sel_tmp12_fu_332_p2);
    sensitive << ( sel_tmp_reg_684 );
    sensitive << ( sel_tmp11_fu_326_p2 );

    SC_METHOD(thread_sel_tmp14_fu_242_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_fu_206_p2 );
    sensitive << ( i_reg_114 );

    SC_METHOD(thread_sel_tmp24_fu_337_p2);
    sensitive << ( sel_tmp14_reg_690 );
    sensitive << ( sel_tmp11_fu_326_p2 );

    SC_METHOD(thread_sel_tmp29_fu_248_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_fu_206_p2 );
    sensitive << ( i_reg_114 );

    SC_METHOD(thread_sel_tmp30_fu_254_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_fu_206_p2 );
    sensitive << ( i_reg_114 );

    SC_METHOD(thread_sel_tmp31_fu_260_p2);
    sensitive << ( sel_tmp29_fu_248_p2 );
    sensitive << ( sel_tmp30_fu_254_p2 );

    SC_METHOD(thread_sel_tmp32_fu_342_p2);
    sensitive << ( sel_tmp31_reg_698 );
    sensitive << ( sel_tmp11_fu_326_p2 );

    SC_METHOD(thread_sel_tmp39_fu_347_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( j_reg_126 );

    SC_METHOD(thread_sel_tmp40_fu_353_p2);
    sensitive << ( sel_tmp14_reg_690 );
    sensitive << ( sel_tmp39_fu_347_p2 );

    SC_METHOD(thread_sel_tmp48_fu_358_p2);
    sensitive << ( sel_tmp31_reg_698 );
    sensitive << ( sel_tmp39_fu_347_p2 );

    SC_METHOD(thread_sel_tmp5_fu_308_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( j_reg_126 );

    SC_METHOD(thread_sel_tmp7_fu_314_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( j_reg_126 );

    SC_METHOD(thread_sel_tmp_fu_236_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_fu_206_p2 );
    sensitive << ( i_reg_114 );

    SC_METHOD(thread_tmp2_fu_320_p2);
    sensitive << ( sel_tmp5_fu_308_p2 );
    sensitive << ( sel_tmp7_fu_314_p2 );

    SC_METHOD(thread_tmp3_fu_363_p2);
    sensitive << ( sel_tmp11_fu_326_p2 );
    sensitive << ( tmp2_fu_320_p2 );

    SC_METHOD(thread_tmp5_fu_374_p2);
    sensitive << ( sel_tmp_reg_684 );
    sensitive << ( sel_tmp14_reg_690 );

    SC_METHOD(thread_tmp_1_fu_291_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond6_fu_270_p2 );
    sensitive << ( tmp_s_fu_282_p2 );

    SC_METHOD(thread_tmp_1_fu_291_p1);
    sensitive << ( tmp_1_fu_291_p0 );

    SC_METHOD(thread_tmp_98_fu_296_p2);
    sensitive << ( i_reg_114 );
    sensitive << ( j_reg_126 );

    SC_METHOD(thread_tmp_99_fu_302_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond6_fu_270_p2 );
    sensitive << ( tmp_98_fu_296_p2 );

    SC_METHOD(thread_tmp_fu_230_p2);
    sensitive << ( p_shl_cast_fu_226_p1 );
    sensitive << ( i_cast_fu_202_p1 );

    SC_METHOD(thread_tmp_s_fu_282_p2);
    sensitive << ( tmp_reg_679 );
    sensitive << ( j_cast_fu_266_p1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_64 );
    sensitive << ( exitcond_fu_206_p2 );
    sensitive << ( exitcond6_fu_270_p2 );
    sensitive << ( grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_done );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "000";
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_start_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "Sobel_1_0_3_16_16_1080_1920_1080_1920_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    const char* dump_vcd = std::getenv("AP_WRITE_VCD");
    if (dump_vcd && string(dump_vcd) == "1" ) {
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, p_src_rows_V_read, "(port)p_src_rows_V_read");
    sc_trace(mVcdFile, p_src_cols_V_read, "(port)p_src_cols_V_read");
    sc_trace(mVcdFile, p_src_data_stream_0_V_dout, "(port)p_src_data_stream_0_V_dout");
    sc_trace(mVcdFile, p_src_data_stream_0_V_empty_n, "(port)p_src_data_stream_0_V_empty_n");
    sc_trace(mVcdFile, p_src_data_stream_0_V_read, "(port)p_src_data_stream_0_V_read");
    sc_trace(mVcdFile, p_src_data_stream_1_V_dout, "(port)p_src_data_stream_1_V_dout");
    sc_trace(mVcdFile, p_src_data_stream_1_V_empty_n, "(port)p_src_data_stream_1_V_empty_n");
    sc_trace(mVcdFile, p_src_data_stream_1_V_read, "(port)p_src_data_stream_1_V_read");
    sc_trace(mVcdFile, p_src_data_stream_2_V_dout, "(port)p_src_data_stream_2_V_dout");
    sc_trace(mVcdFile, p_src_data_stream_2_V_empty_n, "(port)p_src_data_stream_2_V_empty_n");
    sc_trace(mVcdFile, p_src_data_stream_2_V_read, "(port)p_src_data_stream_2_V_read");
    sc_trace(mVcdFile, p_dst_data_stream_0_V_din, "(port)p_dst_data_stream_0_V_din");
    sc_trace(mVcdFile, p_dst_data_stream_0_V_full_n, "(port)p_dst_data_stream_0_V_full_n");
    sc_trace(mVcdFile, p_dst_data_stream_0_V_write, "(port)p_dst_data_stream_0_V_write");
    sc_trace(mVcdFile, p_dst_data_stream_1_V_din, "(port)p_dst_data_stream_1_V_din");
    sc_trace(mVcdFile, p_dst_data_stream_1_V_full_n, "(port)p_dst_data_stream_1_V_full_n");
    sc_trace(mVcdFile, p_dst_data_stream_1_V_write, "(port)p_dst_data_stream_1_V_write");
    sc_trace(mVcdFile, p_dst_data_stream_2_V_din, "(port)p_dst_data_stream_2_V_din");
    sc_trace(mVcdFile, p_dst_data_stream_2_V_full_n, "(port)p_dst_data_stream_2_V_full_n");
    sc_trace(mVcdFile, p_dst_data_stream_2_V_write, "(port)p_dst_data_stream_2_V_write");
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, a_address0, "a_address0");
    sc_trace(mVcdFile, a_ce0, "a_ce0");
    sc_trace(mVcdFile, a_q0, "a_q0");
    sc_trace(mVcdFile, ap_sig_bdd_64, "ap_sig_bdd_64");
    sc_trace(mVcdFile, i_1_fu_212_p2, "i_1_fu_212_p2");
    sc_trace(mVcdFile, i_1_reg_674, "i_1_reg_674");
    sc_trace(mVcdFile, tmp_fu_230_p2, "tmp_fu_230_p2");
    sc_trace(mVcdFile, tmp_reg_679, "tmp_reg_679");
    sc_trace(mVcdFile, exitcond_fu_206_p2, "exitcond_fu_206_p2");
    sc_trace(mVcdFile, sel_tmp_fu_236_p2, "sel_tmp_fu_236_p2");
    sc_trace(mVcdFile, sel_tmp_reg_684, "sel_tmp_reg_684");
    sc_trace(mVcdFile, sel_tmp14_fu_242_p2, "sel_tmp14_fu_242_p2");
    sc_trace(mVcdFile, sel_tmp14_reg_690, "sel_tmp14_reg_690");
    sc_trace(mVcdFile, sel_tmp31_fu_260_p2, "sel_tmp31_fu_260_p2");
    sc_trace(mVcdFile, sel_tmp31_reg_698, "sel_tmp31_reg_698");
    sc_trace(mVcdFile, j_1_fu_276_p2, "j_1_fu_276_p2");
    sc_trace(mVcdFile, j_1_reg_752, "j_1_reg_752");
    sc_trace(mVcdFile, exitcond6_fu_270_p2, "exitcond6_fu_270_p2");
    sc_trace(mVcdFile, tmp_99_fu_302_p2, "tmp_99_fu_302_p2");
    sc_trace(mVcdFile, tmp_99_reg_762, "tmp_99_reg_762");
    sc_trace(mVcdFile, a_load_reg_769, "a_load_reg_769");
    sc_trace(mVcdFile, sel_tmp12_fu_332_p2, "sel_tmp12_fu_332_p2");
    sc_trace(mVcdFile, sel_tmp12_reg_774, "sel_tmp12_reg_774");
    sc_trace(mVcdFile, sel_tmp24_fu_337_p2, "sel_tmp24_fu_337_p2");
    sc_trace(mVcdFile, sel_tmp24_reg_780, "sel_tmp24_reg_780");
    sc_trace(mVcdFile, sel_tmp32_fu_342_p2, "sel_tmp32_fu_342_p2");
    sc_trace(mVcdFile, sel_tmp32_reg_786, "sel_tmp32_reg_786");
    sc_trace(mVcdFile, sel_tmp40_fu_353_p2, "sel_tmp40_fu_353_p2");
    sc_trace(mVcdFile, sel_tmp40_reg_791, "sel_tmp40_reg_791");
    sc_trace(mVcdFile, sel_tmp48_fu_358_p2, "sel_tmp48_fu_358_p2");
    sc_trace(mVcdFile, sel_tmp48_reg_797, "sel_tmp48_reg_797");
    sc_trace(mVcdFile, or_cond7_fu_369_p2, "or_cond7_fu_369_p2");
    sc_trace(mVcdFile, or_cond7_reg_804, "or_cond7_reg_804");
    sc_trace(mVcdFile, or_cond12_fu_378_p2, "or_cond12_fu_378_p2");
    sc_trace(mVcdFile, or_cond12_reg_811, "or_cond12_reg_811");
    sc_trace(mVcdFile, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_start, "grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_start");
    sc_trace(mVcdFile, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_done, "grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_done");
    sc_trace(mVcdFile, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_idle, "grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_idle");
    sc_trace(mVcdFile, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_ready, "grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_ready");
    sc_trace(mVcdFile, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_0_V_dout, "grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_0_V_dout");
    sc_trace(mVcdFile, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_0_V_empty_n, "grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_0_V_empty_n");
    sc_trace(mVcdFile, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_0_V_read, "grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_0_V_read");
    sc_trace(mVcdFile, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_1_V_dout, "grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_1_V_dout");
    sc_trace(mVcdFile, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_1_V_empty_n, "grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_1_V_empty_n");
    sc_trace(mVcdFile, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_1_V_read, "grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_1_V_read");
    sc_trace(mVcdFile, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_2_V_dout, "grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_2_V_dout");
    sc_trace(mVcdFile, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_2_V_empty_n, "grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_2_V_empty_n");
    sc_trace(mVcdFile, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_2_V_read, "grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_2_V_read");
    sc_trace(mVcdFile, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_0_V_din, "grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_0_V_din");
    sc_trace(mVcdFile, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_0_V_full_n, "grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_0_V_full_n");
    sc_trace(mVcdFile, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_0_V_write, "grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_0_V_write");
    sc_trace(mVcdFile, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_1_V_din, "grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_1_V_din");
    sc_trace(mVcdFile, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_1_V_full_n, "grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_1_V_full_n");
    sc_trace(mVcdFile, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_1_V_write, "grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_1_V_write");
    sc_trace(mVcdFile, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_2_V_din, "grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_2_V_din");
    sc_trace(mVcdFile, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_2_V_full_n, "grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_2_V_full_n");
    sc_trace(mVcdFile, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_2_V_write, "grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_2_V_write");
    sc_trace(mVcdFile, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_0_0_V_read, "grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_0_0_V_read");
    sc_trace(mVcdFile, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_0_1_V_read, "grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_0_1_V_read");
    sc_trace(mVcdFile, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_0_2_V_read, "grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_0_2_V_read");
    sc_trace(mVcdFile, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_1_0_V_read, "grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_1_0_V_read");
    sc_trace(mVcdFile, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_1_1_V_read, "grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_1_1_V_read");
    sc_trace(mVcdFile, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_1_2_V_read, "grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_1_2_V_read");
    sc_trace(mVcdFile, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_2_0_V_read, "grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_2_0_V_read");
    sc_trace(mVcdFile, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_2_1_V_read, "grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_2_1_V_read");
    sc_trace(mVcdFile, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_2_2_V_read, "grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_2_2_V_read");
    sc_trace(mVcdFile, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_rows, "grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_rows");
    sc_trace(mVcdFile, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_cols, "grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_cols");
    sc_trace(mVcdFile, i_reg_114, "i_reg_114");
    sc_trace(mVcdFile, j_reg_126, "j_reg_126");
    sc_trace(mVcdFile, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_start_ap_start_reg, "grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_start_ap_start_reg");
    sc_trace(mVcdFile, tmp_1_fu_291_p1, "tmp_1_fu_291_p1");
    sc_trace(mVcdFile, kernel_val_0_0_V_fu_54, "kernel_val_0_0_V_fu_54");
    sc_trace(mVcdFile, kernel_val_2_2_V_16_fu_554_p3, "kernel_val_2_2_V_16_fu_554_p3");
    sc_trace(mVcdFile, kernel_val_0_1_V_fu_58, "kernel_val_0_1_V_fu_58");
    sc_trace(mVcdFile, kernel_val_2_2_V_15_fu_539_p3, "kernel_val_2_2_V_15_fu_539_p3");
    sc_trace(mVcdFile, kernel_val_0_2_V_1_fu_62, "kernel_val_0_2_V_1_fu_62");
    sc_trace(mVcdFile, kernel_val_0_2_V_fu_517_p3, "kernel_val_0_2_V_fu_517_p3");
    sc_trace(mVcdFile, kernel_val_1_0_V_fu_66, "kernel_val_1_0_V_fu_66");
    sc_trace(mVcdFile, kernel_val_2_2_V_14_fu_488_p3, "kernel_val_2_2_V_14_fu_488_p3");
    sc_trace(mVcdFile, kernel_val_1_1_V_fu_70, "kernel_val_1_1_V_fu_70");
    sc_trace(mVcdFile, kernel_val_2_2_V_13_fu_473_p3, "kernel_val_2_2_V_13_fu_473_p3");
    sc_trace(mVcdFile, kernel_val_1_2_V_fu_74, "kernel_val_1_2_V_fu_74");
    sc_trace(mVcdFile, kernel_val_2_2_V_12_fu_458_p3, "kernel_val_2_2_V_12_fu_458_p3");
    sc_trace(mVcdFile, kernel_val_2_0_V_fu_78, "kernel_val_2_0_V_fu_78");
    sc_trace(mVcdFile, kernel_val_2_2_V_11_fu_437_p3, "kernel_val_2_2_V_11_fu_437_p3");
    sc_trace(mVcdFile, kernel_val_2_1_V_fu_82, "kernel_val_2_1_V_fu_82");
    sc_trace(mVcdFile, kernel_val_2_2_V_10_fu_429_p3, "kernel_val_2_2_V_10_fu_429_p3");
    sc_trace(mVcdFile, kernel_val_2_2_V_1_fu_86, "kernel_val_2_2_V_1_fu_86");
    sc_trace(mVcdFile, kernel_val_2_2_V_fu_406_p3, "kernel_val_2_2_V_fu_406_p3");
    sc_trace(mVcdFile, p_shl_fu_218_p3, "p_shl_fu_218_p3");
    sc_trace(mVcdFile, p_shl_cast_fu_226_p1, "p_shl_cast_fu_226_p1");
    sc_trace(mVcdFile, i_cast_fu_202_p1, "i_cast_fu_202_p1");
    sc_trace(mVcdFile, sel_tmp29_fu_248_p2, "sel_tmp29_fu_248_p2");
    sc_trace(mVcdFile, sel_tmp30_fu_254_p2, "sel_tmp30_fu_254_p2");
    sc_trace(mVcdFile, j_cast_fu_266_p1, "j_cast_fu_266_p1");
    sc_trace(mVcdFile, tmp_s_fu_282_p2, "tmp_s_fu_282_p2");
    sc_trace(mVcdFile, tmp_1_fu_291_p0, "tmp_1_fu_291_p0");
    sc_trace(mVcdFile, tmp_98_fu_296_p2, "tmp_98_fu_296_p2");
    sc_trace(mVcdFile, sel_tmp5_fu_308_p2, "sel_tmp5_fu_308_p2");
    sc_trace(mVcdFile, sel_tmp7_fu_314_p2, "sel_tmp7_fu_314_p2");
    sc_trace(mVcdFile, sel_tmp11_fu_326_p2, "sel_tmp11_fu_326_p2");
    sc_trace(mVcdFile, sel_tmp39_fu_347_p2, "sel_tmp39_fu_347_p2");
    sc_trace(mVcdFile, tmp2_fu_320_p2, "tmp2_fu_320_p2");
    sc_trace(mVcdFile, tmp3_fu_363_p2, "tmp3_fu_363_p2");
    sc_trace(mVcdFile, tmp5_fu_374_p2, "tmp5_fu_374_p2");
    sc_trace(mVcdFile, or_cond_fu_387_p2, "or_cond_fu_387_p2");
    sc_trace(mVcdFile, or_cond5_fu_391_p2, "or_cond5_fu_391_p2");
    sc_trace(mVcdFile, or_cond11_fu_395_p2, "or_cond11_fu_395_p2");
    sc_trace(mVcdFile, or_cond13_fu_401_p2, "or_cond13_fu_401_p2");
    sc_trace(mVcdFile, kernel_val_2_2_V_fu_406_p2, "kernel_val_2_2_V_fu_406_p2");
    sc_trace(mVcdFile, kernel_val_2_0_V_3_fu_384_p1, "kernel_val_2_0_V_3_fu_384_p1");
    sc_trace(mVcdFile, newSel20_fu_414_p2, "newSel20_fu_414_p2");
    sc_trace(mVcdFile, newSel20_fu_414_p3, "newSel20_fu_414_p3");
    sc_trace(mVcdFile, newSel22_fu_421_p3, "newSel22_fu_421_p3");
    sc_trace(mVcdFile, kernel_val_2_2_V_11_fu_437_p1, "kernel_val_2_2_V_11_fu_437_p1");
    sc_trace(mVcdFile, newSel30_fu_444_p2, "newSel30_fu_444_p2");
    sc_trace(mVcdFile, newSel30_fu_444_p3, "newSel30_fu_444_p3");
    sc_trace(mVcdFile, newSel34_fu_451_p3, "newSel34_fu_451_p3");
    sc_trace(mVcdFile, newSel36_fu_466_p1, "newSel36_fu_466_p1");
    sc_trace(mVcdFile, newSel36_fu_466_p3, "newSel36_fu_466_p3");
    sc_trace(mVcdFile, kernel_val_2_2_V_6_fu_481_p1, "kernel_val_2_2_V_6_fu_481_p1");
    sc_trace(mVcdFile, kernel_val_2_2_V_6_fu_481_p3, "kernel_val_2_2_V_6_fu_481_p3");
    sc_trace(mVcdFile, newSel37_fu_495_p2, "newSel37_fu_495_p2");
    sc_trace(mVcdFile, newSel37_fu_495_p3, "newSel37_fu_495_p3");
    sc_trace(mVcdFile, newSel38_fu_502_p3, "newSel38_fu_502_p3");
    sc_trace(mVcdFile, newSel39_fu_509_p3, "newSel39_fu_509_p3");
    sc_trace(mVcdFile, newSel_fu_525_p1, "newSel_fu_525_p1");
    sc_trace(mVcdFile, newSel_fu_525_p3, "newSel_fu_525_p3");
    sc_trace(mVcdFile, newSel40_fu_532_p3, "newSel40_fu_532_p3");
    sc_trace(mVcdFile, newSel41_fu_547_p1, "newSel41_fu_547_p1");
    sc_trace(mVcdFile, newSel41_fu_547_p3, "newSel41_fu_547_p3");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");

    }
}

Sobel_1_0_3_16_16_1080_1920_1080_1920_s::~Sobel_1_0_3_16_16_1080_1920_1080_1920_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete a_U;
    delete grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139;
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,3,3>(ap_ST_st6_fsm_5, ap_CS_fsm.read()) && 
                    !esl_seteq<1,1,1>(ap_const_logic_0, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_done.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_start_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,3,3>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && 
             !esl_seteq<1,1,1>(exitcond_fu_206_p2.read(), ap_const_lv1_0))) {
            grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_start_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_ready.read())) {
            grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_start_ap_start_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,3,3>(ap_ST_st3_fsm_2, ap_CS_fsm.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_fu_270_p2.read()))) {
        i_reg_114 = i_1_reg_674.read();
    } else if ((esl_seteq<1,3,3>(ap_ST_st1_fsm_0, ap_CS_fsm.read()) && 
                !ap_sig_bdd_64.read())) {
        i_reg_114 = ap_const_lv2_0;
    }
    if (esl_seteq<1,3,3>(ap_ST_st5_fsm_4, ap_CS_fsm.read())) {
        j_reg_126 = j_1_reg_752.read();
    } else if ((esl_seteq<1,3,3>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && 
                esl_seteq<1,1,1>(exitcond_fu_206_p2.read(), ap_const_lv1_0))) {
        j_reg_126 = ap_const_lv2_0;
    }
    if (esl_seteq<1,3,3>(ap_ST_st4_fsm_3, ap_CS_fsm.read())) {
        a_load_reg_769 = a_q0.read();
        or_cond12_reg_811 = or_cond12_fu_378_p2.read();
        or_cond7_reg_804 = or_cond7_fu_369_p2.read();
        sel_tmp12_reg_774 = sel_tmp12_fu_332_p2.read();
        sel_tmp24_reg_780 = sel_tmp24_fu_337_p2.read();
        sel_tmp32_reg_786 = sel_tmp32_fu_342_p2.read();
        sel_tmp40_reg_791 = sel_tmp40_fu_353_p2.read();
        sel_tmp48_reg_797 = sel_tmp48_fu_358_p2.read();
    }
    if (esl_seteq<1,3,3>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        i_1_reg_674 = i_1_fu_212_p2.read();
    }
    if (esl_seteq<1,3,3>(ap_ST_st3_fsm_2, ap_CS_fsm.read())) {
        j_1_reg_752 = j_1_fu_276_p2.read();
    }
    if (esl_seteq<1,3,3>(ap_ST_st5_fsm_4, ap_CS_fsm.read())) {
        kernel_val_0_0_V_fu_54 = kernel_val_2_2_V_16_fu_554_p3.read();
        kernel_val_0_1_V_fu_58 = kernel_val_2_2_V_15_fu_539_p3.read();
        kernel_val_0_2_V_1_fu_62 = kernel_val_0_2_V_fu_517_p3.read();
        kernel_val_1_0_V_fu_66 = kernel_val_2_2_V_14_fu_488_p3.read();
        kernel_val_1_1_V_fu_70 = kernel_val_2_2_V_13_fu_473_p3.read();
        kernel_val_1_2_V_fu_74 = kernel_val_2_2_V_12_fu_458_p3.read();
        kernel_val_2_0_V_fu_78 = kernel_val_2_2_V_11_fu_437_p3.read();
        kernel_val_2_1_V_fu_82 = kernel_val_2_2_V_10_fu_429_p3.read();
        kernel_val_2_2_V_1_fu_86 = kernel_val_2_2_V_fu_406_p3.read();
    }
    if ((esl_seteq<1,3,3>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && esl_seteq<1,1,1>(exitcond_fu_206_p2.read(), ap_const_lv1_0))) {
        sel_tmp14_reg_690 = sel_tmp14_fu_242_p2.read();
        sel_tmp31_reg_698 = sel_tmp31_fu_260_p2.read();
        sel_tmp_reg_684 = sel_tmp_fu_236_p2.read();
        tmp_reg_679 = tmp_fu_230_p2.read();
    }
    if ((esl_seteq<1,3,3>(ap_ST_st3_fsm_2, ap_CS_fsm.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_fu_270_p2.read()))) {
        tmp_99_reg_762 = tmp_99_fu_302_p2.read();
    }
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_a_address0() {
    a_address0 =  (sc_lv<4>) (tmp_1_fu_291_p1.read());
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_a_ce0() {
    if ((esl_seteq<1,3,3>(ap_ST_st3_fsm_2, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_fu_270_p2.read()))) {
        a_ce0 = ap_const_logic_1;
    } else {
        a_ce0 = ap_const_logic_0;
    }
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_done_reg.read()) || 
         (esl_seteq<1,3,3>(ap_ST_st6_fsm_5, ap_CS_fsm.read()) && 
          !esl_seteq<1,1,1>(ap_const_logic_0, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_done.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,3,3>(ap_ST_st1_fsm_0, ap_CS_fsm.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_ap_ready() {
    if ((esl_seteq<1,3,3>(ap_ST_st6_fsm_5, ap_CS_fsm.read()) && 
         !esl_seteq<1,1,1>(ap_const_logic_0, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_done.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_ap_sig_bdd_64() {
    ap_sig_bdd_64 = (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_exitcond6_fu_270_p2() {
    exitcond6_fu_270_p2 = (!j_reg_126.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(j_reg_126.read() == ap_const_lv2_3);
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_exitcond_fu_206_p2() {
    exitcond_fu_206_p2 = (!i_reg_114.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_114.read() == ap_const_lv2_3);
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_start() {
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_start = grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_start_ap_start_reg.read();
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_cols() {
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_cols = p_src_cols_V_read.read();
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_0_0_V_read() {
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_0_0_V_read = kernel_val_0_0_V_fu_54.read();
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_0_1_V_read() {
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_0_1_V_read = kernel_val_0_1_V_fu_58.read();
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_0_2_V_read() {
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_0_2_V_read = kernel_val_0_2_V_1_fu_62.read();
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_1_0_V_read() {
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_1_0_V_read = kernel_val_1_0_V_fu_66.read();
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_1_1_V_read() {
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_1_1_V_read = kernel_val_1_1_V_fu_70.read();
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_1_2_V_read() {
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_1_2_V_read = kernel_val_1_2_V_fu_74.read();
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_2_0_V_read() {
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_2_0_V_read = kernel_val_2_0_V_fu_78.read();
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_2_1_V_read() {
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_2_1_V_read = kernel_val_2_1_V_fu_82.read();
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_2_2_V_read() {
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_kernel_val_2_2_V_read = kernel_val_2_2_V_1_fu_86.read();
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_0_V_full_n() {
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_0_V_full_n = p_dst_data_stream_0_V_full_n.read();
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_1_V_full_n() {
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_1_V_full_n = p_dst_data_stream_1_V_full_n.read();
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_2_V_full_n() {
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_2_V_full_n = p_dst_data_stream_2_V_full_n.read();
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_0_V_dout() {
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_0_V_dout = p_src_data_stream_0_V_dout.read();
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_0_V_empty_n() {
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_0_V_empty_n = p_src_data_stream_0_V_empty_n.read();
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_1_V_dout() {
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_1_V_dout = p_src_data_stream_1_V_dout.read();
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_1_V_empty_n() {
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_1_V_empty_n = p_src_data_stream_1_V_empty_n.read();
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_2_V_dout() {
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_2_V_dout = p_src_data_stream_2_V_dout.read();
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_2_V_empty_n() {
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_2_V_empty_n = p_src_data_stream_2_V_empty_n.read();
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_rows() {
    grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_rows = p_src_rows_V_read.read();
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_i_1_fu_212_p2() {
    i_1_fu_212_p2 = (!i_reg_114.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_bigint<2>(i_reg_114.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_i_cast_fu_202_p1() {
    i_cast_fu_202_p1 = esl_zext<5,2>(i_reg_114.read());
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_j_1_fu_276_p2() {
    j_1_fu_276_p2 = (!j_reg_126.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_bigint<2>(j_reg_126.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_j_cast_fu_266_p1() {
    j_cast_fu_266_p1 = esl_zext<5,2>(j_reg_126.read());
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_kernel_val_0_2_V_fu_517_p3() {
    kernel_val_0_2_V_fu_517_p3 = (!or_cond13_fu_401_p2.read()[0].is_01())? sc_lv<8>(): ((or_cond13_fu_401_p2.read()[0].to_bool())? newSel39_fu_509_p3.read(): kernel_val_0_2_V_1_fu_62.read());
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_kernel_val_2_0_V_3_fu_384_p1() {
    kernel_val_2_0_V_3_fu_384_p1 = esl_sext<8,3>(a_load_reg_769.read());
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_kernel_val_2_2_V_10_fu_429_p3() {
    kernel_val_2_2_V_10_fu_429_p3 = (!or_cond11_fu_395_p2.read()[0].is_01())? sc_lv<8>(): ((or_cond11_fu_395_p2.read()[0].to_bool())? newSel22_fu_421_p3.read(): kernel_val_2_1_V_fu_82.read());
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_kernel_val_2_2_V_11_fu_437_p1() {
    kernel_val_2_2_V_11_fu_437_p1 = kernel_val_2_0_V_3_fu_384_p1.read();
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_kernel_val_2_2_V_11_fu_437_p3() {
    kernel_val_2_2_V_11_fu_437_p3 = (!sel_tmp48_reg_797.read()[0].is_01())? sc_lv<8>(): ((sel_tmp48_reg_797.read()[0].to_bool())? kernel_val_2_2_V_11_fu_437_p1.read(): kernel_val_2_0_V_fu_78.read());
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_kernel_val_2_2_V_12_fu_458_p3() {
    kernel_val_2_2_V_12_fu_458_p3 = (!or_cond11_fu_395_p2.read()[0].is_01())? sc_lv<8>(): ((or_cond11_fu_395_p2.read()[0].to_bool())? kernel_val_1_2_V_fu_74.read(): newSel34_fu_451_p3.read());
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_kernel_val_2_2_V_13_fu_473_p3() {
    kernel_val_2_2_V_13_fu_473_p3 = (!or_cond11_fu_395_p2.read()[0].is_01())? sc_lv<8>(): ((or_cond11_fu_395_p2.read()[0].to_bool())? kernel_val_1_1_V_fu_70.read(): newSel36_fu_466_p3.read());
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_kernel_val_2_2_V_14_fu_488_p3() {
    kernel_val_2_2_V_14_fu_488_p3 = (!sel_tmp48_reg_797.read()[0].is_01())? sc_lv<8>(): ((sel_tmp48_reg_797.read()[0].to_bool())? kernel_val_1_0_V_fu_66.read(): kernel_val_2_2_V_6_fu_481_p3.read());
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_kernel_val_2_2_V_15_fu_539_p3() {
    kernel_val_2_2_V_15_fu_539_p3 = (!or_cond11_fu_395_p2.read()[0].is_01())? sc_lv<8>(): ((or_cond11_fu_395_p2.read()[0].to_bool())? kernel_val_0_1_V_fu_58.read(): newSel40_fu_532_p3.read());
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_kernel_val_2_2_V_16_fu_554_p3() {
    kernel_val_2_2_V_16_fu_554_p3 = (!or_cond_fu_387_p2.read()[0].is_01())? sc_lv<8>(): ((or_cond_fu_387_p2.read()[0].to_bool())? kernel_val_0_0_V_fu_54.read(): newSel41_fu_547_p3.read());
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_kernel_val_2_2_V_6_fu_481_p1() {
    kernel_val_2_2_V_6_fu_481_p1 = kernel_val_2_0_V_3_fu_384_p1.read();
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_kernel_val_2_2_V_6_fu_481_p3() {
    kernel_val_2_2_V_6_fu_481_p3 = (!sel_tmp40_reg_791.read()[0].is_01())? sc_lv<8>(): ((sel_tmp40_reg_791.read()[0].to_bool())? kernel_val_2_2_V_6_fu_481_p1.read(): kernel_val_1_0_V_fu_66.read());
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_kernel_val_2_2_V_fu_406_p2() {
    kernel_val_2_2_V_fu_406_p2 = kernel_val_2_0_V_3_fu_384_p1.read();
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_kernel_val_2_2_V_fu_406_p3() {
    kernel_val_2_2_V_fu_406_p3 = (!or_cond13_fu_401_p2.read()[0].is_01())? sc_lv<8>(): ((or_cond13_fu_401_p2.read()[0].to_bool())? kernel_val_2_2_V_1_fu_86.read(): kernel_val_2_2_V_fu_406_p2.read());
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_newSel20_fu_414_p2() {
    newSel20_fu_414_p2 = kernel_val_2_0_V_3_fu_384_p1.read();
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_newSel20_fu_414_p3() {
    newSel20_fu_414_p3 = (!tmp_99_reg_762.read()[0].is_01())? sc_lv<8>(): ((tmp_99_reg_762.read()[0].to_bool())? kernel_val_2_1_V_fu_82.read(): newSel20_fu_414_p2.read());
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_newSel22_fu_421_p3() {
    newSel22_fu_421_p3 = (!or_cond_fu_387_p2.read()[0].is_01())? sc_lv<8>(): ((or_cond_fu_387_p2.read()[0].to_bool())? kernel_val_2_1_V_fu_82.read(): newSel20_fu_414_p3.read());
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_newSel30_fu_444_p2() {
    newSel30_fu_444_p2 = kernel_val_2_0_V_3_fu_384_p1.read();
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_newSel30_fu_444_p3() {
    newSel30_fu_444_p3 = (!sel_tmp24_reg_780.read()[0].is_01())? sc_lv<8>(): ((sel_tmp24_reg_780.read()[0].to_bool())? kernel_val_1_2_V_fu_74.read(): newSel30_fu_444_p2.read());
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_newSel34_fu_451_p3() {
    newSel34_fu_451_p3 = (!or_cond7_reg_804.read()[0].is_01())? sc_lv<8>(): ((or_cond7_reg_804.read()[0].to_bool())? newSel30_fu_444_p3.read(): kernel_val_1_2_V_fu_74.read());
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_newSel36_fu_466_p1() {
    newSel36_fu_466_p1 = kernel_val_2_0_V_3_fu_384_p1.read();
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_newSel36_fu_466_p3() {
    newSel36_fu_466_p3 = (!sel_tmp24_reg_780.read()[0].is_01())? sc_lv<8>(): ((sel_tmp24_reg_780.read()[0].to_bool())? newSel36_fu_466_p1.read(): kernel_val_1_1_V_fu_70.read());
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_newSel37_fu_495_p2() {
    newSel37_fu_495_p2 = kernel_val_2_0_V_3_fu_384_p1.read();
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_newSel37_fu_495_p3() {
    newSel37_fu_495_p3 = (!sel_tmp12_reg_774.read()[0].is_01())? sc_lv<8>(): ((sel_tmp12_reg_774.read()[0].to_bool())? kernel_val_0_2_V_1_fu_62.read(): newSel37_fu_495_p2.read());
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_newSel38_fu_502_p3() {
    newSel38_fu_502_p3 = (!or_cond7_reg_804.read()[0].is_01())? sc_lv<8>(): ((or_cond7_reg_804.read()[0].to_bool())? kernel_val_0_2_V_1_fu_62.read(): newSel37_fu_495_p3.read());
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_newSel39_fu_509_p3() {
    newSel39_fu_509_p3 = (!or_cond11_fu_395_p2.read()[0].is_01())? sc_lv<8>(): ((or_cond11_fu_395_p2.read()[0].to_bool())? kernel_val_0_2_V_1_fu_62.read(): newSel38_fu_502_p3.read());
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_newSel40_fu_532_p3() {
    newSel40_fu_532_p3 = (!or_cond7_reg_804.read()[0].is_01())? sc_lv<8>(): ((or_cond7_reg_804.read()[0].to_bool())? kernel_val_0_1_V_fu_58.read(): newSel_fu_525_p3.read());
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_newSel41_fu_547_p1() {
    newSel41_fu_547_p1 = kernel_val_2_0_V_3_fu_384_p1.read();
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_newSel41_fu_547_p3() {
    newSel41_fu_547_p3 = (!tmp_99_reg_762.read()[0].is_01())? sc_lv<8>(): ((tmp_99_reg_762.read()[0].to_bool())? newSel41_fu_547_p1.read(): kernel_val_0_0_V_fu_54.read());
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_newSel_fu_525_p1() {
    newSel_fu_525_p1 = kernel_val_2_0_V_3_fu_384_p1.read();
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_newSel_fu_525_p3() {
    newSel_fu_525_p3 = (!sel_tmp12_reg_774.read()[0].is_01())? sc_lv<8>(): ((sel_tmp12_reg_774.read()[0].to_bool())? newSel_fu_525_p1.read(): kernel_val_0_1_V_fu_58.read());
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_or_cond11_fu_395_p2() {
    or_cond11_fu_395_p2 = (or_cond_fu_387_p2.read() | or_cond5_fu_391_p2.read());
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_or_cond12_fu_378_p2() {
    or_cond12_fu_378_p2 = (tmp3_fu_363_p2.read() & tmp5_fu_374_p2.read());
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_or_cond13_fu_401_p2() {
    or_cond13_fu_401_p2 = (or_cond11_fu_395_p2.read() | or_cond12_reg_811.read());
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_or_cond5_fu_391_p2() {
    or_cond5_fu_391_p2 = (tmp_99_reg_762.read() | sel_tmp32_reg_786.read());
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_or_cond7_fu_369_p2() {
    or_cond7_fu_369_p2 = (sel_tmp14_reg_690.read() & tmp3_fu_363_p2.read());
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_or_cond_fu_387_p2() {
    or_cond_fu_387_p2 = (sel_tmp48_reg_797.read() | sel_tmp40_reg_791.read());
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_p_dst_data_stream_0_V_din() {
    p_dst_data_stream_0_V_din = grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_0_V_din.read();
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_p_dst_data_stream_0_V_write() {
    if ((esl_seteq<1,3,3>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) || 
         esl_seteq<1,3,3>(ap_ST_st6_fsm_5, ap_CS_fsm.read()))) {
        p_dst_data_stream_0_V_write = grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_0_V_write.read();
    } else {
        p_dst_data_stream_0_V_write = ap_const_logic_0;
    }
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_p_dst_data_stream_1_V_din() {
    p_dst_data_stream_1_V_din = grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_1_V_din.read();
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_p_dst_data_stream_1_V_write() {
    if ((esl_seteq<1,3,3>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) || 
         esl_seteq<1,3,3>(ap_ST_st6_fsm_5, ap_CS_fsm.read()))) {
        p_dst_data_stream_1_V_write = grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_1_V_write.read();
    } else {
        p_dst_data_stream_1_V_write = ap_const_logic_0;
    }
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_p_dst_data_stream_2_V_din() {
    p_dst_data_stream_2_V_din = grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_2_V_din.read();
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_p_dst_data_stream_2_V_write() {
    if ((esl_seteq<1,3,3>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) || 
         esl_seteq<1,3,3>(ap_ST_st6_fsm_5, ap_CS_fsm.read()))) {
        p_dst_data_stream_2_V_write = grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_dst_data_stream_2_V_write.read();
    } else {
        p_dst_data_stream_2_V_write = ap_const_logic_0;
    }
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_p_shl_cast_fu_226_p1() {
    p_shl_cast_fu_226_p1 = esl_zext<5,4>(p_shl_fu_218_p3.read());
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_p_shl_fu_218_p3() {
    p_shl_fu_218_p3 = esl_concat<2,2>(i_reg_114.read(), ap_const_lv2_0);
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_p_src_data_stream_0_V_read() {
    if ((esl_seteq<1,3,3>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) || 
         esl_seteq<1,3,3>(ap_ST_st6_fsm_5, ap_CS_fsm.read()))) {
        p_src_data_stream_0_V_read = grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_0_V_read.read();
    } else {
        p_src_data_stream_0_V_read = ap_const_logic_0;
    }
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_p_src_data_stream_1_V_read() {
    if ((esl_seteq<1,3,3>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) || 
         esl_seteq<1,3,3>(ap_ST_st6_fsm_5, ap_CS_fsm.read()))) {
        p_src_data_stream_1_V_read = grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_1_V_read.read();
    } else {
        p_src_data_stream_1_V_read = ap_const_logic_0;
    }
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_p_src_data_stream_2_V_read() {
    if ((esl_seteq<1,3,3>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) || 
         esl_seteq<1,3,3>(ap_ST_st6_fsm_5, ap_CS_fsm.read()))) {
        p_src_data_stream_2_V_read = grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_p_src_data_stream_2_V_read.read();
    } else {
        p_src_data_stream_2_V_read = ap_const_logic_0;
    }
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_sel_tmp11_fu_326_p2() {
    sel_tmp11_fu_326_p2 = (!j_reg_126.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(j_reg_126.read() == ap_const_lv2_1);
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_sel_tmp12_fu_332_p2() {
    sel_tmp12_fu_332_p2 = (sel_tmp_reg_684.read() & sel_tmp11_fu_326_p2.read());
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_sel_tmp14_fu_242_p2() {
    sel_tmp14_fu_242_p2 = (!i_reg_114.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_114.read() == ap_const_lv2_1);
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_sel_tmp24_fu_337_p2() {
    sel_tmp24_fu_337_p2 = (sel_tmp14_reg_690.read() & sel_tmp11_fu_326_p2.read());
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_sel_tmp29_fu_248_p2() {
    sel_tmp29_fu_248_p2 = (!i_reg_114.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_114.read() != ap_const_lv2_0);
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_sel_tmp30_fu_254_p2() {
    sel_tmp30_fu_254_p2 = (!i_reg_114.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_114.read() != ap_const_lv2_1);
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_sel_tmp31_fu_260_p2() {
    sel_tmp31_fu_260_p2 = (sel_tmp29_fu_248_p2.read() & sel_tmp30_fu_254_p2.read());
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_sel_tmp32_fu_342_p2() {
    sel_tmp32_fu_342_p2 = (sel_tmp31_reg_698.read() & sel_tmp11_fu_326_p2.read());
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_sel_tmp39_fu_347_p2() {
    sel_tmp39_fu_347_p2 = (!j_reg_126.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(j_reg_126.read() == ap_const_lv2_0);
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_sel_tmp40_fu_353_p2() {
    sel_tmp40_fu_353_p2 = (sel_tmp14_reg_690.read() & sel_tmp39_fu_347_p2.read());
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_sel_tmp48_fu_358_p2() {
    sel_tmp48_fu_358_p2 = (sel_tmp31_reg_698.read() & sel_tmp39_fu_347_p2.read());
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_sel_tmp5_fu_308_p2() {
    sel_tmp5_fu_308_p2 = (!j_reg_126.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(j_reg_126.read() != ap_const_lv2_0);
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_sel_tmp7_fu_314_p2() {
    sel_tmp7_fu_314_p2 = (!j_reg_126.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(j_reg_126.read() != ap_const_lv2_1);
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_sel_tmp_fu_236_p2() {
    sel_tmp_fu_236_p2 = (!i_reg_114.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_114.read() == ap_const_lv2_0);
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_tmp2_fu_320_p2() {
    tmp2_fu_320_p2 = (sel_tmp5_fu_308_p2.read() & sel_tmp7_fu_314_p2.read());
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_tmp3_fu_363_p2() {
    tmp3_fu_363_p2 = (tmp2_fu_320_p2.read() | sel_tmp11_fu_326_p2.read());
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_tmp5_fu_374_p2() {
    tmp5_fu_374_p2 = (sel_tmp14_reg_690.read() | sel_tmp_reg_684.read());
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_tmp_1_fu_291_p0() {
    tmp_1_fu_291_p0 = esl_sext<32,5>(tmp_s_fu_282_p2.read());
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_tmp_1_fu_291_p1() {
    tmp_1_fu_291_p1 = esl_zext<64,32>(tmp_1_fu_291_p0.read());
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_tmp_98_fu_296_p2() {
    tmp_98_fu_296_p2 = (i_reg_114.read() | j_reg_126.read());
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_tmp_99_fu_302_p2() {
    tmp_99_fu_302_p2 = (!tmp_98_fu_296_p2.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_98_fu_296_p2.read() == ap_const_lv2_0);
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_tmp_fu_230_p2() {
    tmp_fu_230_p2 = (!p_shl_cast_fu_226_p1.read().is_01() || !i_cast_fu_202_p1.read().is_01())? sc_lv<5>(): (sc_bigint<5>(p_shl_cast_fu_226_p1.read()) - sc_biguint<5>(i_cast_fu_202_p1.read()));
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_tmp_s_fu_282_p2() {
    tmp_s_fu_282_p2 = (!tmp_reg_679.read().is_01() || !j_cast_fu_266_p1.read().is_01())? sc_lv<5>(): (sc_bigint<5>(tmp_reg_679.read()) + sc_biguint<5>(j_cast_fu_266_p1.read()));
}

void Sobel_1_0_3_16_16_1080_1920_1080_1920_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint()) {
        case 0 : 
            if (!ap_sig_bdd_64.read()) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 1 : 
            if (esl_seteq<1,1,1>(exitcond_fu_206_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            } else {
                ap_NS_fsm = ap_ST_st6_fsm_5;
            }
            break;
        case 2 : 
            if (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_fu_270_p2.read())) {
                ap_NS_fsm = ap_ST_st4_fsm_3;
            } else {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            }
            break;
        case 3 : 
            ap_NS_fsm = ap_ST_st5_fsm_4;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_st3_fsm_2;
            break;
        case 5 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, grp_filter_opr_filter2d_kernel_16_16_ap_int_8_int_1080_1920_3_3_s_fu_139_ap_done.read())) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st6_fsm_5;
            }
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}
}

