// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.2
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _SubS_1080_1920_16_unsigned_char_16_s_HH_
#define _SubS_1080_1920_16_unsigned_char_16_s_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct SubS_1080_1920_16_unsigned_char_16_s : public sc_module {
    // Port declarations 29
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<12> > src_rows_V_read;
    sc_in< sc_lv<12> > src_cols_V_read;
    sc_in< sc_lv<8> > src_data_stream_0_V_dout;
    sc_in< sc_logic > src_data_stream_0_V_empty_n;
    sc_out< sc_logic > src_data_stream_0_V_read;
    sc_in< sc_lv<8> > src_data_stream_1_V_dout;
    sc_in< sc_logic > src_data_stream_1_V_empty_n;
    sc_out< sc_logic > src_data_stream_1_V_read;
    sc_in< sc_lv<8> > src_data_stream_2_V_dout;
    sc_in< sc_logic > src_data_stream_2_V_empty_n;
    sc_out< sc_logic > src_data_stream_2_V_read;
    sc_in< sc_lv<12> > dst_rows_V_read;
    sc_in< sc_lv<12> > dst_cols_V_read;
    sc_out< sc_lv<8> > dst_data_stream_0_V_din;
    sc_in< sc_logic > dst_data_stream_0_V_full_n;
    sc_out< sc_logic > dst_data_stream_0_V_write;
    sc_out< sc_lv<8> > dst_data_stream_1_V_din;
    sc_in< sc_logic > dst_data_stream_1_V_full_n;
    sc_out< sc_logic > dst_data_stream_1_V_write;
    sc_out< sc_lv<8> > dst_data_stream_2_V_din;
    sc_in< sc_logic > dst_data_stream_2_V_full_n;
    sc_out< sc_logic > dst_data_stream_2_V_write;


    // Module declarations
    SubS_1080_1920_16_unsigned_char_16_s(sc_module_name name);
    SC_HAS_PROCESS(SubS_1080_1920_16_unsigned_char_16_s);

    ~SubS_1080_1920_16_unsigned_char_16_s();

    sc_trace_file* mVcdFile;

    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<2> > ap_CS_fsm;
    sc_signal< sc_lv<12> > t_V_5_reg_148;
    sc_signal< bool > ap_sig_bdd_58;
    sc_signal< sc_lv<12> > i_V_fu_165_p2;
    sc_signal< sc_lv<12> > i_V_reg_285;
    sc_signal< sc_lv<1> > exitcond4_fu_171_p2;
    sc_signal< sc_lv<1> > exitcond4_reg_290;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it0;
    sc_signal< bool > ap_sig_bdd_82;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it1;
    sc_signal< sc_lv<1> > ap_reg_ppstg_exitcond4_reg_290_pp0_it1;
    sc_signal< bool > ap_sig_bdd_96;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it2;
    sc_signal< sc_lv<12> > j_V_fu_176_p2;
    sc_signal< sc_lv<8> > tmp_149_reg_299;
    sc_signal< sc_lv<8> > tmp_150_reg_304;
    sc_signal< sc_lv<8> > tmp_151_reg_309;
    sc_signal< sc_lv<1> > exitcond_fu_160_p2;
    sc_signal< sc_lv<12> > t_V_reg_137;
    sc_signal< sc_lv<9> > tmp18_cast_i_fu_182_p1;
    sc_signal< sc_lv<9> > v_assign_fu_185_p2;
    sc_signal< sc_lv<1> > tmp_fu_191_p3;
    sc_signal< sc_lv<8> > tmp_144_fu_199_p1;
    sc_signal< sc_lv<9> > tmp_1_cast_i_fu_212_p1;
    sc_signal< sc_lv<9> > v_assign_3_fu_215_p2;
    sc_signal< sc_lv<1> > tmp_145_fu_221_p3;
    sc_signal< sc_lv<8> > tmp_146_fu_229_p1;
    sc_signal< sc_lv<9> > tmp_2_cast_i_fu_242_p1;
    sc_signal< sc_lv<9> > v_assign_4_fu_245_p2;
    sc_signal< sc_lv<1> > tmp_147_fu_251_p3;
    sc_signal< sc_lv<8> > tmp_148_fu_259_p1;
    sc_signal< sc_lv<2> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<2> ap_ST_st1_fsm_0;
    static const sc_lv<2> ap_ST_st2_fsm_1;
    static const sc_lv<2> ap_ST_pp0_stg0_fsm_2;
    static const sc_lv<2> ap_ST_st6_fsm_3;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<12> ap_const_lv12_0;
    static const sc_lv<12> ap_const_lv12_1;
    static const sc_lv<9> ap_const_lv9_1CE;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<8> ap_const_lv8_0;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sig_bdd_58();
    void thread_ap_sig_bdd_82();
    void thread_ap_sig_bdd_96();
    void thread_dst_data_stream_0_V_din();
    void thread_dst_data_stream_0_V_write();
    void thread_dst_data_stream_1_V_din();
    void thread_dst_data_stream_1_V_write();
    void thread_dst_data_stream_2_V_din();
    void thread_dst_data_stream_2_V_write();
    void thread_exitcond4_fu_171_p2();
    void thread_exitcond_fu_160_p2();
    void thread_i_V_fu_165_p2();
    void thread_j_V_fu_176_p2();
    void thread_src_data_stream_0_V_read();
    void thread_src_data_stream_1_V_read();
    void thread_src_data_stream_2_V_read();
    void thread_tmp18_cast_i_fu_182_p1();
    void thread_tmp_144_fu_199_p1();
    void thread_tmp_145_fu_221_p3();
    void thread_tmp_146_fu_229_p1();
    void thread_tmp_147_fu_251_p3();
    void thread_tmp_148_fu_259_p1();
    void thread_tmp_1_cast_i_fu_212_p1();
    void thread_tmp_2_cast_i_fu_242_p1();
    void thread_tmp_fu_191_p3();
    void thread_v_assign_3_fu_215_p2();
    void thread_v_assign_4_fu_245_p2();
    void thread_v_assign_fu_185_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
